CREATE TABLE IF NOT EXISTS mytrip_weather(
weatherId INT(11) NOT NULL,
Title VARCHAR(256) NOT NULL,
UrlXml VARCHAR(256) NOT NULL,
Culture VARCHAR(50) NOT NULL,
AllCulture BIT(1) NOT NULL,
UserName VARCHAR(100) NOT NULL,
CreateDate DATETIME NOT NULL,            
VisibleInformer BIT(1) NOT NULL,
PRIMARY KEY (weatherId)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 4096
CHARACTER SET cp1251
COLLATE cp1251_general_ci;