//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mtm.Core.Files {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FilesIcon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FilesIcon() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mtm.Core.Files.FilesIcon", typeof(FilesIcon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static byte[] asax {
            get {
                object obj = ResourceManager.GetObject("asax", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] ascx {
            get {
                object obj = ResourceManager.GetObject("ascx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] aspx {
            get {
                object obj = ResourceManager.GetObject("aspx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] cache {
            get {
                object obj = ResourceManager.GetObject("cache", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] config {
            get {
                object obj = ResourceManager.GetObject("config", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] cs {
            get {
                object obj = ResourceManager.GetObject("cs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] cshtml {
            get {
                object obj = ResourceManager.GetObject("cshtml", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] csproj {
            get {
                object obj = ResourceManager.GetObject("csproj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] css {
            get {
                object obj = ResourceManager.GetObject("css", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] dll {
            get {
                object obj = ResourceManager.GetObject("dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] js {
            get {
                object obj = ResourceManager.GetObject("js", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] ldf {
            get {
                object obj = ResourceManager.GetObject("ldf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] master {
            get {
                object obj = ResourceManager.GetObject("master", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] mdf {
            get {
                object obj = ResourceManager.GetObject("mdf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] pdb {
            get {
                object obj = ResourceManager.GetObject("pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] pdf {
            get {
                object obj = ResourceManager.GetObject("pdf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] rar {
            get {
                object obj = ResourceManager.GetObject("rar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] resx {
            get {
                object obj = ResourceManager.GetObject("resx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] txt {
            get {
                object obj = ResourceManager.GetObject("txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] user {
            get {
                object obj = ResourceManager.GetObject("user", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] vspscc {
            get {
                object obj = ResourceManager.GetObject("vspscc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] xml {
            get {
                object obj = ResourceManager.GetObject("xml", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] zip {
            get {
                object obj = ResourceManager.GetObject("zip", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
