CREATE TABLE IF NOT EXISTS mytrip_rssparser(
RssparserId INT(11) NOT NULL,
Title VARCHAR(256) NOT NULL,
Path VARCHAR(256) NOT NULL,
SeoTitle VARCHAR (256) DEFAULT NULL,
SeoKeyword TEXT DEFAULT NULL,
SeoDescription TEXT DEFAULT NULL,
CreateDate DATETIME NOT NULL,
UserName VARCHAR(100) NOT NULL,
Views INT(11) NOT NULL,
Culture VARCHAR(100) NOT NULL,
AllCulture BIT(1) NOT NULL,
RssUrl VARCHAR(256) NOT NULL,
ImageUrl VARCHAR(256) DEFAULT NULL,
PRIMARY KEY (RssparserId)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 4096
CHARACTER SET cp1251
COLLATE cp1251_general_ci;