//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace mtm.Articles.Repository.DataEntities
{
    public partial class mytrip_articles
    {
        #region Primitive Properties
    
        public virtual string Abstract
        {
            get;
            set;
        }
    
        public virtual bool AllCulture
        {
            get;
            set;
        }
    
        public virtual bool ApprovedComment
        {
            get;
            set;
        }
    
        public virtual bool ApprovedVotes
        {
            get;
            set;
        }
    
        public virtual int ArticleId
        {
            get;
            set;
        }
    
        public virtual string Body
        {
            get;
            set;
        }
    
        public virtual string SeoTitle
        {
            get;
            set;
        }
    
        public virtual string SeoKeyword
        {
            get;
            set;
        }
    
        public virtual string SeoDescription
        {
            get;
            set;
        }
    
        public virtual int CategoryId
        {
            get { return _categoryId; }
            set
            {
                if (_categoryId != value)
                {
                    if (mytrip_articlescategory != null && mytrip_articlescategory.CategoryId != value)
                    {
                        mytrip_articlescategory = null;
                    }
                    _categoryId = value;
                }
            }
        }
        private int _categoryId;
    
        public virtual System.DateTime CloseDate
        {
            get;
            set;
        }
    
        public virtual System.DateTime CreateDate
        {
            get;
            set;
        }
    
        public virtual string Culture
        {
            get;
            set;
        }
    
        public virtual string ImageForAbstract
        {
            get;
            set;
        }
    
        public virtual bool IncludeAnonymComment
        {
            get;
            set;
        }
    
        public virtual bool ModerateComments
        {
            get;
            set;
        }
    
        public virtual bool OnlyForRegisterUser
        {
            get;
            set;
        }
    
        public virtual string Path
        {
            get;
            set;
        }
    
        public virtual int SubArticleId
        {
            get { return _subArticleId; }
            set
            {
                if (_subArticleId != value)
                {
                    if (mytrip_articles2 != null && mytrip_articles2.ArticleId != value)
                    {
                        mytrip_articles2 = null;
                    }
                    _subArticleId = value;
                }
            }
        }
        private int _subArticleId;
    
        public virtual string Title
        {
            get;
            set;
        }
    
        public virtual decimal TotalVotes
        {
            get;
            set;
        }
    
        public virtual string UserName
        {
            get;
            set;
        }
    
        public virtual int Views
        {
            get;
            set;
        }
    
        public virtual bool CommentVotes
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<mytrip_articlescomments> mytrip_articlescomments
        {
            get
            {
                if (_mytrip_articlescomments == null)
                {
                    var newCollection = new FixupCollection<mytrip_articlescomments>();
                    newCollection.CollectionChanged += Fixupmytrip_articlescomments;
                    _mytrip_articlescomments = newCollection;
                }
                return _mytrip_articlescomments;
            }
            set
            {
                if (!ReferenceEquals(_mytrip_articlescomments, value))
                {
                    var previousValue = _mytrip_articlescomments as FixupCollection<mytrip_articlescomments>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupmytrip_articlescomments;
                    }
                    _mytrip_articlescomments = value;
                    var newValue = value as FixupCollection<mytrip_articlescomments>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupmytrip_articlescomments;
                    }
                }
            }
        }
        private ICollection<mytrip_articlescomments> _mytrip_articlescomments;
    
        public virtual ICollection<mytrip_articlessubscription> mytrip_articlessubscription
        {
            get
            {
                if (_mytrip_articlessubscription == null)
                {
                    var newCollection = new FixupCollection<mytrip_articlessubscription>();
                    newCollection.CollectionChanged += Fixupmytrip_articlessubscription;
                    _mytrip_articlessubscription = newCollection;
                }
                return _mytrip_articlessubscription;
            }
            set
            {
                if (!ReferenceEquals(_mytrip_articlessubscription, value))
                {
                    var previousValue = _mytrip_articlessubscription as FixupCollection<mytrip_articlessubscription>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupmytrip_articlessubscription;
                    }
                    _mytrip_articlessubscription = value;
                    var newValue = value as FixupCollection<mytrip_articlessubscription>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupmytrip_articlessubscription;
                    }
                }
            }
        }
        private ICollection<mytrip_articlessubscription> _mytrip_articlessubscription;
    
        public virtual ICollection<mytrip_articlesvotes> mytrip_articlesvotes
        {
            get
            {
                if (_mytrip_articlesvotes == null)
                {
                    var newCollection = new FixupCollection<mytrip_articlesvotes>();
                    newCollection.CollectionChanged += Fixupmytrip_articlesvotes;
                    _mytrip_articlesvotes = newCollection;
                }
                return _mytrip_articlesvotes;
            }
            set
            {
                if (!ReferenceEquals(_mytrip_articlesvotes, value))
                {
                    var previousValue = _mytrip_articlesvotes as FixupCollection<mytrip_articlesvotes>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupmytrip_articlesvotes;
                    }
                    _mytrip_articlesvotes = value;
                    var newValue = value as FixupCollection<mytrip_articlesvotes>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupmytrip_articlesvotes;
                    }
                }
            }
        }
        private ICollection<mytrip_articlesvotes> _mytrip_articlesvotes;
    
        public virtual ICollection<mytrip_articles> mytrip_articles1
        {
            get
            {
                if (_mytrip_articles1 == null)
                {
                    var newCollection = new FixupCollection<mytrip_articles>();
                    newCollection.CollectionChanged += Fixupmytrip_articles1;
                    _mytrip_articles1 = newCollection;
                }
                return _mytrip_articles1;
            }
            set
            {
                if (!ReferenceEquals(_mytrip_articles1, value))
                {
                    var previousValue = _mytrip_articles1 as FixupCollection<mytrip_articles>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupmytrip_articles1;
                    }
                    _mytrip_articles1 = value;
                    var newValue = value as FixupCollection<mytrip_articles>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupmytrip_articles1;
                    }
                }
            }
        }
        private ICollection<mytrip_articles> _mytrip_articles1;
    
        public virtual mytrip_articles mytrip_articles2
        {
            get { return _mytrip_articles2; }
            set
            {
                if (!ReferenceEquals(_mytrip_articles2, value))
                {
                    var previousValue = _mytrip_articles2;
                    _mytrip_articles2 = value;
                    Fixupmytrip_articles2(previousValue);
                }
            }
        }
        private mytrip_articles _mytrip_articles2;
    
        public virtual mytrip_articlescategory mytrip_articlescategory
        {
            get { return _mytrip_articlescategory; }
            set
            {
                if (!ReferenceEquals(_mytrip_articlescategory, value))
                {
                    var previousValue = _mytrip_articlescategory;
                    _mytrip_articlescategory = value;
                    Fixupmytrip_articlescategory(previousValue);
                }
            }
        }
        private mytrip_articlescategory _mytrip_articlescategory;
    
        public virtual ICollection<mytrip_articlestag> mytrip_articlestag
        {
            get
            {
                if (_mytrip_articlestag == null)
                {
                    var newCollection = new FixupCollection<mytrip_articlestag>();
                    newCollection.CollectionChanged += Fixupmytrip_articlestag;
                    _mytrip_articlestag = newCollection;
                }
                return _mytrip_articlestag;
            }
            set
            {
                if (!ReferenceEquals(_mytrip_articlestag, value))
                {
                    var previousValue = _mytrip_articlestag as FixupCollection<mytrip_articlestag>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupmytrip_articlestag;
                    }
                    _mytrip_articlestag = value;
                    var newValue = value as FixupCollection<mytrip_articlestag>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupmytrip_articlestag;
                    }
                }
            }
        }
        private ICollection<mytrip_articlestag> _mytrip_articlestag;

        #endregion
        #region Association Fixup
    
        private void Fixupmytrip_articles2(mytrip_articles previousValue)
        {
            if (previousValue != null && previousValue.mytrip_articles1.Contains(this))
            {
                previousValue.mytrip_articles1.Remove(this);
            }
    
            if (mytrip_articles2 != null)
            {
                if (!mytrip_articles2.mytrip_articles1.Contains(this))
                {
                    mytrip_articles2.mytrip_articles1.Add(this);
                }
                if (SubArticleId != mytrip_articles2.ArticleId)
                {
                    SubArticleId = mytrip_articles2.ArticleId;
                }
            }
        }
    
        private void Fixupmytrip_articlescategory(mytrip_articlescategory previousValue)
        {
            if (previousValue != null && previousValue.mytrip_articles.Contains(this))
            {
                previousValue.mytrip_articles.Remove(this);
            }
    
            if (mytrip_articlescategory != null)
            {
                if (!mytrip_articlescategory.mytrip_articles.Contains(this))
                {
                    mytrip_articlescategory.mytrip_articles.Add(this);
                }
                if (CategoryId != mytrip_articlescategory.CategoryId)
                {
                    CategoryId = mytrip_articlescategory.CategoryId;
                }
            }
        }
    
        private void Fixupmytrip_articlescomments(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (mytrip_articlescomments item in e.NewItems)
                {
                    item.mytrip_articles = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (mytrip_articlescomments item in e.OldItems)
                {
                    if (ReferenceEquals(item.mytrip_articles, this))
                    {
                        item.mytrip_articles = null;
                    }
                }
            }
        }
    
        private void Fixupmytrip_articlessubscription(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (mytrip_articlessubscription item in e.NewItems)
                {
                    item.mytrip_articles = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (mytrip_articlessubscription item in e.OldItems)
                {
                    if (ReferenceEquals(item.mytrip_articles, this))
                    {
                        item.mytrip_articles = null;
                    }
                }
            }
        }
    
        private void Fixupmytrip_articlesvotes(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (mytrip_articlesvotes item in e.NewItems)
                {
                    item.mytrip_articles = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (mytrip_articlesvotes item in e.OldItems)
                {
                    if (ReferenceEquals(item.mytrip_articles, this))
                    {
                        item.mytrip_articles = null;
                    }
                }
            }
        }
    
        private void Fixupmytrip_articles1(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (mytrip_articles item in e.NewItems)
                {
                    item.mytrip_articles2 = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (mytrip_articles item in e.OldItems)
                {
                    if (ReferenceEquals(item.mytrip_articles2, this))
                    {
                        item.mytrip_articles2 = null;
                    }
                }
            }
        }
    
        private void Fixupmytrip_articlestag(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (mytrip_articlestag item in e.NewItems)
                {
                    if (!item.mytrip_articles.Contains(this))
                    {
                        item.mytrip_articles.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (mytrip_articlestag item in e.OldItems)
                {
                    if (item.mytrip_articles.Contains(this))
                    {
                        item.mytrip_articles.Remove(this);
                    }
                }
            }
        }

        #endregion
    }
}
