//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mtm.Tourism.Files {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebPages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebPages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mtm.Tourism.Files.WebPages", typeof(WebPages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model mtm.Tourism.Models.EditorCategoryModel
        ///@{ 
        ///    /* Copyright © 2009 - 2010 Oleg Stuhin &amp; Rostislav Haitovich
        ///       To learn more about mytrip.mvc visit
        ///       http://mytripmvc.net  http://mytripmvc.codeplex.com
        ///       mytripmvc@gmail.com
        ///       license: Microsoft Public License (Ms-PL) */
        ///}
        ///@{
        ///    ViewBag.Title = Html.MytripPageTitle(Model.TitlePage, &quot;/&quot;);
        ///    ViewBag.Keywords=Html.MytripPageTitle(Model.TitlePage, &quot;,&quot;);
        ///    ViewBag.Description=Html.MytripPageTitle(Model.TitlePage, &quot;,&quot;);
        ///}
        ///@sectio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EditorCategory {
            get {
                return ResourceManager.GetString("EditorCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model mtm.Tourism.Models.EditorTourModel
        ///@{ 
        ///    /* Copyright © 2009 - 2010 Oleg Stuhin &amp; Rostislav Haitovich
        ///       To learn more about mytrip.mvc visit
        ///       http://mytripmvc.net  http://mytripmvc.codeplex.com
        ///       mytripmvc@gmail.com
        ///       license: Microsoft Public License (Ms-PL) */
        ///}
        ///@{
        ///    ViewBag.Title = Html.MytripPageTitle(Model.TitlePage, &quot;/&quot;);
        ///    ViewBag.Keywords=Html.MytripPageTitle(Model.TitlePage, &quot;,&quot;);
        ///    ViewBag.Description=Html.MytripPageTitle(Model.TitlePage, &quot;,&quot;);
        ///}
        ///@section sc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EditorTour {
            get {
                return ResourceManager.GetString("EditorTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model mtm.Tourism.Models.ToursIndexModel
        ///@{ 
        ///    /* Copyright © 2009 - 2010 Oleg Stuhin &amp; Rostislav Haitovich
        ///       To learn more about mytrip.mvc visit
        ///       http://mytripmvc.net  http://mytripmvc.codeplex.com
        ///       mytripmvc@gmail.com
        ///       license: Microsoft Public License (Ms-PL) */
        ///}
        ///@{
        ///    ViewBag.Title = Html.MytripPageTitle(Model.PageTitle, &quot;/&quot;);
        ///    ViewBag.Keywords=Html.MytripPageTitle(Model.PageTitle, &quot;,&quot;);
        ///    ViewBag.Description=Html.MytripPageTitle(Model.PageTitle, &quot;,&quot;);
        ///}
        ///@section sc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model mtm.Tourism.Models.OrderTourModel
        ///@{ 
        ///    /* Copyright © 2009 - 2010 Oleg Stuhin &amp; Rostislav Haitovich
        ///       To learn more about mytrip.mvc visit
        ///       http://mytripmvc.net  http://mytripmvc.codeplex.com
        ///       mytripmvc@gmail.com
        ///       license: Microsoft Public License (Ms-PL) */
        ///}
        ///@{
        ///    ViewBag.Title = Html.MytripPageTitle(ToursLanguage.ordertour, &quot;/&quot;);
        ///    ViewBag.Keywords=Html.MytripPageTitle(ToursLanguage.ordertour, &quot;,&quot;);
        ///    ViewBag.Description=Html.MytripPageTitle(ToursLanguage.ordertour [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OrderTour {
            get {
                return ResourceManager.GetString("OrderTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model mtm.Tourism.Models.TourViewModel
        ///@{ 
        ///    /* Copyright © 2009 - 2010 Oleg Stuhin &amp; Rostislav Haitovich
        ///       To learn more about mytrip.mvc visit
        ///       http://mytripmvc.net  http://mytripmvc.codeplex.com
        ///       mytripmvc@gmail.com
        ///       license: Microsoft Public License (Ms-PL) */
        ///}
        ///@{
        ///    ViewBag.Title = Html.MytripPageTitle(Model.PageTitle, &quot;/&quot;);
        ///    ViewBag.Keywords=Html.MytripPageTitle(Model.PageTitle, &quot;,&quot;);
        ///    ViewBag.Description=Html.MytripPageTitle(Model.PageTitle, &quot;,&quot;);
        ///}
        ///@section scri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///
        ///&lt;configuration&gt;
        ///   &lt;system.web.webPages.razor&gt;
        ///       &lt;pages pageBaseType=&quot;System.Web.Mvc.WebViewPage&quot;&gt;        
        ///            &lt;namespaces&gt;
        ///                &lt;add namespace=&quot;mtm.Tourism&quot; /&gt;
        ///                &lt;add namespace=&quot;mtm.Tourism.Helpers&quot; /&gt;
        ///            &lt;/namespaces&gt;
        ///        &lt;/pages&gt;
        ///    &lt;/system.web.webPages.razor&gt;
        ///&lt;/configuration&gt;.
        /// </summary>
        internal static string Web {
            get {
                return ResourceManager.GetString("Web", resourceCulture);
            }
        }
    }
}
