using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Mytrip.Core
{
    public class PageSettings
    {
        public static string[] SiteMaster(string param)
        {
            string[] result;
            if (param == "right")
            {
                result = new string[]
        {
"<%@ Master Language=[x_1_x]C#[x_1_x] Inherits=[x_1_x]System.Web.Mvc.ViewMasterPage[x_1_x] %>",
"<!DOCTYPE html PUBLIC [x_1_x]-//W3C//DTD XHTML 1.0 Strict//EN[x_1_x] [x_1_x]http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd[x_1_x]>",
"<html xmlns=[x_1_x]http://www.w3.org/1999/xhtml[x_1_x]>",
"<head runat=[x_1_x]server[x_1_x]>",
"    <%  //************************************************************ ",
"        // Copyright В© 2009 - 2010 Oleg Stuhin & Rostislav Haitovich",
"        // To learn more about Mytrip.Mvc.Entyty visit ",
"        // http://starterkitmytripmvc.codeplex.com/",
"        // mytripmvc@gmail.com",
"        // license: Microsoft Public License (Ms-PL) ",
"        // *********************************************************** %>",
"    <title>",
"        <asp:ContentPlaceHolder ID=[x_1_x]TitleContent[x_1_x] runat=[x_1_x]server[x_1_x] />",
"    </title>",
"    <link href=[x_1_x]/RssArticle/RssArticles[x_1_x] rel=[x_1_x]alternate[x_1_x] type=[x_1_x]application/rss+xml[x_1_x] title=[x_1_x]Articles[x_1_x] />",
"    <link href=[x_1_x]/RssArticle/RssBlogs[x_1_x] rel=[x_1_x]alternate[x_1_x] type=[x_1_x]application/rss+xml[x_1_x] title=[x_1_x]Blogs[x_1_x] />",
"    <%=Html.CssLink() %>",
"    <script src=[x_1_x]/Scripts/jquery-1.3.2.js[x_1_x] type=[x_1_x]text/javascript[x_1_x]></script>",
"    <script src=[x_1_x]/Scripts/mytrip-jquery.js[x_1_x] type=[x_1_x]text/javascript[x_1_x]></script>",
"    <asp:ContentPlaceHolder ID=[x_1_x]ScriptContent[x_1_x] runat=[x_1_x]server[x_1_x] />",
"</head>",
"    <body>",
"    <div class=[x_1_x]page[x_1_x]>",
"        <div id=[x_1_x]header[x_1_x]>",
"            <div id=[x_1_x]title[x_1_x]>",
"                 <%=Html.Logo() %>",
"            </div>",
"            <div id=[x_1_x]topmenudisplay[x_1_x] class=[x_1_x]topmenudisplay[x_1_x]>",
"                <ul>",
"                    <%= Html.LanguageMenu() %>",
"                    <%= Html.ThemeMenu() %>",
"                    <% =Html.LogonMenu()%>",
"                </ul>",
"            </div>",
"            <div id=[x_1_x]menucontainer[x_1_x] class=[x_1_x]menucontainer[x_1_x]>",
"                <ul><%ArticleCache article = new ArticleCache(); %>",
"                    <%= Html.MytripMenu(article.ArticleMenu(), article.CategoryMenu(), article.BlogMenu())%>",
"                </ul>",
"            </div>",
"        </div>",
"        <div id=[x_1_x]main[x_1_x]>",
"            <asp:ContentPlaceHolder ID=[x_1_x]MainContent[x_1_x] runat=[x_1_x]server[x_1_x] />",
"           <table class=[x_1_x]mastertable[x_1_x]>",
"                <tr>",
"                    <td class=[x_1_x]masterrighttd[x_1_x]>",
"                        <asp:ContentPlaceHolder ID=[x_1_x]MainContentLeft[x_1_x] runat=[x_1_x]server[x_1_x] />",
"                    </td>",
"                    <td class=[x_1_x]masterlefttd[x_1_x]>",
"                        <asp:ContentPlaceHolder ID=[x_1_x]MainContentRight[x_1_x] runat=[x_1_x]server[x_1_x] />",
"                    </td>",
"                </tr>",
"            </table>",
"            <div id=[x_1_x]footer[x_1_x]>",
"                Copyright В© 2009 - 2010 Oleg Stuhin & Rostislav Haitovich",
"            </div>",
"        </div>",
"    </div>",
"</body>",
"</html>"};
            }
            else
            {
                result = new string[] {
"<%@ Master Language=[x_1_x]C#[x_1_x] Inherits=[x_1_x]System.Web.Mvc.ViewMasterPage[x_1_x] %>",
"<!DOCTYPE html PUBLIC [x_1_x]-//W3C//DTD XHTML 1.0 Strict//EN[x_1_x] [x_1_x]http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd[x_1_x]>",
"<html xmlns=[x_1_x]http://www.w3.org/1999/xhtml[x_1_x]>",
"<head runat=[x_1_x]server[x_1_x]>",
"    <%  //************************************************************ ",
"        // Copyright В© 2009 - 2010 Oleg Stuhin & Rostislav Haitovich",
"        // To learn more about Mytrip.Mvc.Entyty visit ",
"        // http://starterkitmytripmvc.codeplex.com/",
"        // mytripmvc@gmail.com",
"        // license: Microsoft Public License (Ms-PL) ",
"        // *********************************************************** %>",
"    <title>",
"        <asp:ContentPlaceHolder ID=[x_1_x]TitleContent[x_1_x] runat=[x_1_x]server[x_1_x] />",
"    </title>",
"    <link href=[x_1_x]/RssArticle/RssArticles[x_1_x] rel=[x_1_x]alternate[x_1_x] type=[x_1_x]application/rss+xml[x_1_x] title=[x_1_x]Articles[x_1_x] />",
"    <link href=[x_1_x]/RssArticle/RssBlogs[x_1_x] rel=[x_1_x]alternate[x_1_x] type=[x_1_x]application/rss+xml[x_1_x] title=[x_1_x]Blogs[x_1_x] />",
"    <%=Html.CssLink() %>",
"    <script src=[x_1_x]/Scripts/jquery-1.3.2.js[x_1_x] type=[x_1_x]text/javascript[x_1_x]></script>",
"    <script src=[x_1_x]/Scripts/mytrip-jquery.js[x_1_x] type=[x_1_x]text/javascript[x_1_x]></script>",
"    <asp:ContentPlaceHolder ID=[x_1_x]ScriptContent[x_1_x] runat=[x_1_x]server[x_1_x] />",
"</head>",
"    <body>",
"    <div class=[x_1_x]page[x_1_x]>",
"        <div id=[x_1_x]header[x_1_x]>",
"            <div id=[x_1_x]title[x_1_x]>",
"                 <%=Html.Logo() %>",
"            </div>",
"            <div id=[x_1_x]topmenudisplay[x_1_x] class=[x_1_x]topmenudisplay[x_1_x]>",
"                <ul>",
"                    <%= Html.LanguageMenu() %>",
"                    <%= Html.ThemeMenu() %>",
"                    <% =Html.LogonMenu()%>",
"                </ul>",
"            </div>",
"            <div id=[x_1_x]menucontainer[x_1_x] class=[x_1_x]menucontainer[x_1_x]>",
"                <ul><%ArticleCache article = new ArticleCache(); %>",
"                    <%= Html.MytripMenu(article.ArticleMenu(), article.CategoryMenu(), article.BlogMenu())%>",
"                </ul>",
"            </div>",
"        </div>",
"        <div id=[x_1_x]main[x_1_x]>",
"            <asp:ContentPlaceHolder ID=[x_1_x]MainContent[x_1_x] runat=[x_1_x]server[x_1_x] />",
"           <table class=[x_1_x]mastertable[x_1_x]>",
"                <tr>",
"                    <td class=[x_1_x]masterlefttd[x_1_x]>",
"                        <asp:ContentPlaceHolder ID=[x_1_x]MainContentRight[x_1_x] runat=[x_1_x]server[x_1_x] />",
"                    </td>",
"                    <td class=[x_1_x]masterrighttd1[x_1_x]>",
"                        <asp:ContentPlaceHolder ID=[x_1_x]MainContentLeft[x_1_x] runat=[x_1_x]server[x_1_x] />",
"                    </td>",
"                </tr>",
"            </table>",
"            <div id=[x_1_x]footer[x_1_x]>",
"                Copyright В© 2009 - 2010 Oleg Stuhin & Rostislav Haitovich",
"            </div>",
"        </div>",
"    </div>",
"</body>",
"</html>" };
            } return result;
        }

    }
}
