//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace mtm.Store.Repository.DataEntities
{
    public partial class mytrip_storeprofile
    {
        #region Primitive Properties
    
        public virtual string Address
        {
            get;
            set;
        }
    
        public virtual string FirstName
        {
            get;
            set;
        }
    
        public virtual bool IsAnonym
        {
            get;
            set;
        }
    
        public virtual string LastName
        {
            get;
            set;
        }
    
        public virtual string Organization
        {
            get;
            set;
        }
    
        public virtual string OrganizationINN
        {
            get;
            set;
        }
    
        public virtual string OrganizationKPP
        {
            get;
            set;
        }
    
        public virtual string Phone
        {
            get;
            set;
        }
    
        public virtual int ProfileId
        {
            get;
            set;
        }
    
        public virtual string UserEmail
        {
            get;
            set;
        }
    
        public virtual string UserIP
        {
            get;
            set;
        }
    
        public virtual string UserName
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<mytrip_storeorder> mytrip_storeorder
        {
            get
            {
                if (_mytrip_storeorder == null)
                {
                    var newCollection = new FixupCollection<mytrip_storeorder>();
                    newCollection.CollectionChanged += Fixupmytrip_storeorder;
                    _mytrip_storeorder = newCollection;
                }
                return _mytrip_storeorder;
            }
            set
            {
                if (!ReferenceEquals(_mytrip_storeorder, value))
                {
                    var previousValue = _mytrip_storeorder as FixupCollection<mytrip_storeorder>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupmytrip_storeorder;
                    }
                    _mytrip_storeorder = value;
                    var newValue = value as FixupCollection<mytrip_storeorder>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupmytrip_storeorder;
                    }
                }
            }
        }
        private ICollection<mytrip_storeorder> _mytrip_storeorder;

        #endregion
        #region Association Fixup
    
        private void Fixupmytrip_storeorder(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (mytrip_storeorder item in e.NewItems)
                {
                    item.mytrip_storeprofile = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (mytrip_storeorder item in e.OldItems)
                {
                    if (ReferenceEquals(item.mytrip_storeprofile, this))
                    {
                        item.mytrip_storeprofile = null;
                    }
                }
            }
        }

        #endregion
    }
}
