//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mtm.Core.Wrap {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NoWrapRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NoWrapRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mtm.Core.Wrap.NoWrapRes", typeof(NoWrapRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul class=&quot;logon&quot;&gt;.
        /// </summary>
        public static string Logon_0 {
            get {
                return ResourceManager.GetString("Logon_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul class=&quot;menu&quot;&gt;.
        /// </summary>
        public static string Menu_0 {
            get {
                return ResourceManager.GetString("Menu_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string Menu_1 {
            get {
                return ResourceManager.GetString("Menu_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;&lt;li&gt;{1}&lt;/li&gt;&lt;/ul&gt;.
        /// </summary>
        public static string Menu_2 {
            get {
                return ResourceManager.GetString("Menu_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Menu_3 {
            get {
                return ResourceManager.GetString("Menu_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li class=&quot;{0}{1}&quot;&gt;.
        /// </summary>
        public static string Menu_4 {
            get {
                return ResourceManager.GetString("Menu_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&lt;/li&gt;.
        /// </summary>
        public static string Menu_5 {
            get {
                return ResourceManager.GetString("Menu_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/ul&gt;.
        /// </summary>
        public static string Menu_6 {
            get {
                return ResourceManager.GetString("Menu_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StyleTable1_0 {
            get {
                return ResourceManager.GetString("StyleTable1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;&lt;td style=&quot;{0}&quot;&gt;{1}&lt;/td&gt;&lt;/tr&gt;.
        /// </summary>
        public static string StyleTable1_1 {
            get {
                return ResourceManager.GetString("StyleTable1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;&lt;td style=&quot;{0}&quot;&gt;{1}&lt;/td&gt;&lt;/tr&gt;.
        /// </summary>
        public static string StyleTable1_2 {
            get {
                return ResourceManager.GetString("StyleTable1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;&lt;td style=&quot;{0}&quot;&gt;{1}&lt;/td&gt;.
        /// </summary>
        public static string StyleTable1_3 {
            get {
                return ResourceManager.GetString("StyleTable1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;&lt;td style=&quot;{0}&quot;&gt;{1}&lt;/td&gt;.
        /// </summary>
        public static string StyleTable1_4 {
            get {
                return ResourceManager.GetString("StyleTable1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td style=&quot;{0}&quot;&gt;{1}&lt;/td&gt;&lt;/tr&gt;.
        /// </summary>
        public static string StyleTable1_5 {
            get {
                return ResourceManager.GetString("StyleTable1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td style=&quot;{0}&quot;&gt;{1}&lt;/td&gt;&lt;/tr&gt;.
        /// </summary>
        public static string StyleTable1_6 {
            get {
                return ResourceManager.GetString("StyleTable1_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td style=&quot;{0}&quot;&gt;{1}&lt;/td&gt;.
        /// </summary>
        public static string StyleTable1_7 {
            get {
                return ResourceManager.GetString("StyleTable1_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td style=&quot;{0}&quot;&gt;{1}&lt;/td&gt;.
        /// </summary>
        public static string StyleTable1_8 {
            get {
                return ResourceManager.GetString("StyleTable1_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StyleTable1_9 {
            get {
                return ResourceManager.GetString("StyleTable1_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StyleTable2_1 {
            get {
                return ResourceManager.GetString("StyleTable2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StyleTable2_10 {
            get {
                return ResourceManager.GetString("StyleTable2_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td  style=&quot;{0}&quot;&gt;{1}&lt;/td&gt;.
        /// </summary>
        public static string StyleTable2_11 {
            get {
                return ResourceManager.GetString("StyleTable2_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to separate.
        /// </summary>
        public static string StyleTable2_12 {
            get {
                return ResourceManager.GetString("StyleTable2_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/td&gt;.
        /// </summary>
        public static string StyleTable2_13 {
            get {
                return ResourceManager.GetString("StyleTable2_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StyleTable2_14 {
            get {
                return ResourceManager.GetString("StyleTable2_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StyleTable2_15 {
            get {
                return ResourceManager.GetString("StyleTable2_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StyleTable2_16 {
            get {
                return ResourceManager.GetString("StyleTable2_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td style=&quot;{0}&quot;&gt;.
        /// </summary>
        public static string StyleTable2_17 {
            get {
                return ResourceManager.GetString("StyleTable2_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td id=&quot;{1}&quot; style=&quot;{0}&quot;&gt;.
        /// </summary>
        public static string StyleTable2_17_2 {
            get {
                return ResourceManager.GetString("StyleTable2_17_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td style=&quot;{0}&quot;&gt;.
        /// </summary>
        public static string StyleTable2_18 {
            get {
                return ResourceManager.GetString("StyleTable2_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td style=&quot;{0}{1}&quot;&gt;.
        /// </summary>
        public static string StyleTable2_18_1 {
            get {
                return ResourceManager.GetString("StyleTable2_18_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td id=&quot;{1}&quot; style=&quot;{0}&quot;&gt;.
        /// </summary>
        public static string StyleTable2_18_2 {
            get {
                return ResourceManager.GetString("StyleTable2_18_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StyleTable2_19 {
            get {
                return ResourceManager.GetString("StyleTable2_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;&lt;td  style=&quot;{0}&quot;&gt;{1}&lt;/td&gt;&lt;/tr&gt;.
        /// </summary>
        public static string StyleTable2_2 {
            get {
                return ResourceManager.GetString("StyleTable2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StyleTable2_20 {
            get {
                return ResourceManager.GetString("StyleTable2_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StyleTable2_21 {
            get {
                return ResourceManager.GetString("StyleTable2_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StyleTable2_22 {
            get {
                return ResourceManager.GetString("StyleTable2_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StyleTable2_3 {
            get {
                return ResourceManager.GetString("StyleTable2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to null.
        /// </summary>
        public static string StyleTable2_4 {
            get {
                return ResourceManager.GetString("StyleTable2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StyleTable2_5 {
            get {
                return ResourceManager.GetString("StyleTable2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;&lt;td style=&quot;{0}&quot;&gt;{1}&lt;/td&gt;.
        /// </summary>
        public static string StyleTable2_6 {
            get {
                return ResourceManager.GetString("StyleTable2_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/tr&gt;.
        /// </summary>
        public static string StyleTable2_7 {
            get {
                return ResourceManager.GetString("StyleTable2_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td  style=&quot;{0}&quot;&gt;{1}&lt;/td&gt;&lt;/tr&gt;.
        /// </summary>
        public static string StyleTable2_8 {
            get {
                return ResourceManager.GetString("StyleTable2_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StyleTable2_9 {
            get {
                return ResourceManager.GetString("StyleTable2_9", resourceCulture);
            }
        }
    }
}
