//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Mytrip.Articles.Repository.DataEntities
{
    public partial class mytrip_articlessubscription
    {
        #region Primitive Properties
    
        public virtual int ArticleId
        {
            get { return _articleId; }
            set
            {
                if (_articleId != value)
                {
                    if (mytrip_articles != null && mytrip_articles.ArticleId != value)
                    {
                        mytrip_articles = null;
                    }
                    _articleId = value;
                }
            }
        }
        private int _articleId;
    
        public virtual int SubscribeId
        {
            get;
            set;
        }
    
        public virtual string UserName
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual mytrip_articles mytrip_articles
        {
            get { return _mytrip_articles; }
            set
            {
                if (!ReferenceEquals(_mytrip_articles, value))
                {
                    var previousValue = _mytrip_articles;
                    _mytrip_articles = value;
                    Fixupmytrip_articles(previousValue);
                }
            }
        }
        private mytrip_articles _mytrip_articles;

        #endregion
        #region Association Fixup
    
        private void Fixupmytrip_articles(mytrip_articles previousValue)
        {
            if (previousValue != null && previousValue.mytrip_articlessubscription.Contains(this))
            {
                previousValue.mytrip_articlessubscription.Remove(this);
            }
    
            if (mytrip_articles != null)
            {
                if (!mytrip_articles.mytrip_articlessubscription.Contains(this))
                {
                    mytrip_articles.mytrip_articlessubscription.Add(this);
                }
                if (ArticleId != mytrip_articles.ArticleId)
                {
                    ArticleId = mytrip_articles.ArticleId;
                }
            }
        }

        #endregion
    }
}
