//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mytrip.Store {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StoreLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StoreLanguage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mytrip.Store.StoreLanguage", typeof(StoreLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for.
        /// </summary>
        public static string _for {
            get {
                return ResourceManager.GetString("_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Department.
        /// </summary>
        public static string AllDepartment {
            get {
                return ResourceManager.GetString("AllDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Producer.
        /// </summary>
        public static string AllProducer {
            get {
                return ResourceManager.GetString("AllProducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date .
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department:.
        /// </summary>
        public static string department {
            get {
                return ResourceManager.GetString("department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to found.
        /// </summary>
        public static string found {
            get {
                return ResourceManager.GetString("found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price from:.
        /// </summary>
        public static string Price_from {
            get {
                return ResourceManager.GetString("Price_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to:.
        /// </summary>
        public static string Price_to {
            get {
                return ResourceManager.GetString("Price_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prise:.
        /// </summary>
        public static string Prise {
            get {
                return ResourceManager.GetString("Prise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prise.
        /// </summary>
        public static string prise_ {
            get {
                return ResourceManager.GetString("prise_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producer:.
        /// </summary>
        public static string Producer {
            get {
                return ResourceManager.GetString("Producer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producers.
        /// </summary>
        public static string Producers {
            get {
                return ResourceManager.GetString("Producers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results.
        /// </summary>
        public static string results {
            get {
                return ResourceManager.GetString("results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by:.
        /// </summary>
        public static string Sorted {
            get {
                return ResourceManager.GetString("Sorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubDepartment:.
        /// </summary>
        public static string subdepartment {
            get {
                return ResourceManager.GetString("subdepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to votes.
        /// </summary>
        public static string votes {
            get {
                return ResourceManager.GetString("votes", resourceCulture);
            }
        }
    }
}
