//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mtm.Core.Files {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SmilesCollection {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SmilesCollection() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mtm.Core.Files.SmilesCollection", typeof(SmilesCollection).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static byte[] _as {
            get {
                object obj = ResourceManager.GetObject("_as", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] aa {
            get {
                object obj = ResourceManager.GetObject("aa", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] ab {
            get {
                object obj = ResourceManager.GetObject("ab", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] ac {
            get {
                object obj = ResourceManager.GetObject("ac", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] ad {
            get {
                object obj = ResourceManager.GetObject("ad", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] ae {
            get {
                object obj = ResourceManager.GetObject("ae", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] af {
            get {
                object obj = ResourceManager.GetObject("af", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] ag {
            get {
                object obj = ResourceManager.GetObject("ag", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] ah {
            get {
                object obj = ResourceManager.GetObject("ah", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] ai {
            get {
                object obj = ResourceManager.GetObject("ai", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] aj {
            get {
                object obj = ResourceManager.GetObject("aj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] ak {
            get {
                object obj = ResourceManager.GetObject("ak", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] al {
            get {
                object obj = ResourceManager.GetObject("al", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] am {
            get {
                object obj = ResourceManager.GetObject("am", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] an {
            get {
                object obj = ResourceManager.GetObject("an", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] ao {
            get {
                object obj = ResourceManager.GetObject("ao", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] ap {
            get {
                object obj = ResourceManager.GetObject("ap", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] aq {
            get {
                object obj = ResourceManager.GetObject("aq", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] ar {
            get {
                object obj = ResourceManager.GetObject("ar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] at {
            get {
                object obj = ResourceManager.GetObject("at", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] au {
            get {
                object obj = ResourceManager.GetObject("au", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] av {
            get {
                object obj = ResourceManager.GetObject("av", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] aw {
            get {
                object obj = ResourceManager.GetObject("aw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] ax {
            get {
                object obj = ResourceManager.GetObject("ax", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] ay {
            get {
                object obj = ResourceManager.GetObject("ay", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] az {
            get {
                object obj = ResourceManager.GetObject("az", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] ba {
            get {
                object obj = ResourceManager.GetObject("ba", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] bb {
            get {
                object obj = ResourceManager.GetObject("bb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] bc {
            get {
                object obj = ResourceManager.GetObject("bc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] bd {
            get {
                object obj = ResourceManager.GetObject("bd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] be {
            get {
                object obj = ResourceManager.GetObject("be", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] bf {
            get {
                object obj = ResourceManager.GetObject("bf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] bg {
            get {
                object obj = ResourceManager.GetObject("bg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] bh {
            get {
                object obj = ResourceManager.GetObject("bh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] bi {
            get {
                object obj = ResourceManager.GetObject("bi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] bj {
            get {
                object obj = ResourceManager.GetObject("bj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] bk {
            get {
                object obj = ResourceManager.GetObject("bk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] bl {
            get {
                object obj = ResourceManager.GetObject("bl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] bm {
            get {
                object obj = ResourceManager.GetObject("bm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] bn {
            get {
                object obj = ResourceManager.GetObject("bn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] bo {
            get {
                object obj = ResourceManager.GetObject("bo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] bp {
            get {
                object obj = ResourceManager.GetObject("bp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] bq {
            get {
                object obj = ResourceManager.GetObject("bq", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] br {
            get {
                object obj = ResourceManager.GetObject("br", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] bs {
            get {
                object obj = ResourceManager.GetObject("bs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] bt {
            get {
                object obj = ResourceManager.GetObject("bt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] bu {
            get {
                object obj = ResourceManager.GetObject("bu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] bv {
            get {
                object obj = ResourceManager.GetObject("bv", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] bw {
            get {
                object obj = ResourceManager.GetObject("bw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] bx {
            get {
                object obj = ResourceManager.GetObject("bx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] ca {
            get {
                object obj = ResourceManager.GetObject("ca", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] cd {
            get {
                object obj = ResourceManager.GetObject("cd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] ce {
            get {
                object obj = ResourceManager.GetObject("ce", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] ch {
            get {
                object obj = ResourceManager.GetObject("ch", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] ci {
            get {
                object obj = ResourceManager.GetObject("ci", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
