//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mtm.Tourism.Files {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mtm.Tourism.Files.JScripts", typeof(JScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var jHtmlArea_API = new Object();
        ///var identity = &apos;&apos;;
        ///$(document).ready(function () {
        ///    $.ajax({ type: &quot;POST&quot;,
        ///        url: &quot;/mtm/Theme&quot;,
        ///        success: function (data) {
        ///            $(&apos;#article&apos;).htmlarea({
        ///                css: &apos;/Theme/&apos; + data + &apos;/TextAreaContainer.css&apos;,
        ///                toolbar: [
        ///            [&quot;html&quot;], [&quot;|&quot;], [&quot;bold&quot;, &quot;italic&quot;, &quot;underline&quot;, &quot;strikethrough&quot;], [&quot;|&quot;], [&quot;subscript&quot;, &quot;superscript&quot;], [&quot;|&quot;],
        ///
        ///         [&quot;smile&quot;], [&quot;|&quot;],
        ///        [&quot;cut&quot;, &quot;copy&quot;, &quot;paste&quot;]
        ///        ]
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tour_editorcategory {
            get {
                return ResourceManager.GetString("tour_editorcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var jHtmlArea_API = new Object();
        ///var identity = &apos;&apos;;
        ///$(document).ready(function () {
        ///    $.ajax({ type: &quot;POST&quot;,
        ///        url: &quot;/mtm/Theme&quot;,
        ///        success: function (data) {
        ///            $(&apos;#article&apos;).htmlarea({
        ///                css: &apos;/Theme/&apos; + data + &apos;/TextAreaContainer.css&apos;,
        ///                toolbar: [
        ///            [&quot;html&quot;], [&quot;|&quot;], [&quot;bold&quot;, &quot;italic&quot;, &quot;underline&quot;, &quot;strikethrough&quot;], [&quot;|&quot;], [&quot;subscript&quot;, &quot;superscript&quot;], [&quot;|&quot;],
        ///
        ///         [{
        ///             css: &apos;smile&apos;, text: &apos;Smiles&apos;, action: function  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tour_editortour {
            get {
                return ResourceManager.GetString("tour_editortour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $(function () {
        ///    $(&apos;#StartDate&apos;).datepicker({
        ///        changeMonth: true,
        ///        changeYear: true,
        ///        dateFormat: &apos;yy-mm-dd&apos;
        ///    });
        ///    $(&apos;#StopDate&apos;).datepicker({
        ///        changeMonth: true,
        ///        changeYear: true,
        ///        dateFormat: &apos;yy-mm-dd&apos;
        ///    });
        ///});.
        /// </summary>
        internal static string tour_ordertour {
            get {
                return ResourceManager.GetString("tour_ordertour", resourceCulture);
            }
        }
    }
}
