//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace mtm.Votes.Repository.DataEntities
{
    public partial class Entities : ObjectContext
    {
        public const string ConnectionString = "name=Entities";
        public const string ContainerName = "Entities";
    
        #region Constructors
    
        public Entities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
        }
    
        public Entities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
        }
    
        public Entities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<mytrip_votesanswer> mytrip_votesanswer
        {
            get { return _mytrip_votesanswer  ?? (_mytrip_votesanswer = CreateObjectSet<mytrip_votesanswer>("mytrip_votesanswer")); }
        }
        private ObjectSet<mytrip_votesanswer> _mytrip_votesanswer;
    
        public ObjectSet<mytrip_votesquestion> mytrip_votesquestion
        {
            get { return _mytrip_votesquestion  ?? (_mytrip_votesquestion = CreateObjectSet<mytrip_votesquestion>("mytrip_votesquestion")); }
        }
        private ObjectSet<mytrip_votesquestion> _mytrip_votesquestion;

        #endregion
    }
}
