//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace mtm.Tourism.Repository.DataEntities
{
    public partial class Entities : ObjectContext
    {
        public const string ConnectionString = "name=Entities";
        public const string ContainerName = "Entities";
    
        #region Constructors
    
        public Entities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
        }
    
        public Entities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
        }
    
        public Entities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<mytrip_tours> mytrip_tours
        {
            get { return _mytrip_tours  ?? (_mytrip_tours = CreateObjectSet<mytrip_tours>("mytrip_tours")); }
        }
        private ObjectSet<mytrip_tours> _mytrip_tours;
    
        public ObjectSet<mytrip_tourscategory> mytrip_tourscategory
        {
            get { return _mytrip_tourscategory  ?? (_mytrip_tourscategory = CreateObjectSet<mytrip_tourscategory>("mytrip_tourscategory")); }
        }
        private ObjectSet<mytrip_tourscategory> _mytrip_tourscategory;
    
        public ObjectSet<mytrip_toursvariants> mytrip_toursvariants
        {
            get { return _mytrip_toursvariants  ?? (_mytrip_toursvariants = CreateObjectSet<mytrip_toursvariants>("mytrip_toursvariants")); }
        }
        private ObjectSet<mytrip_toursvariants> _mytrip_toursvariants;

        #endregion
    }
}
