//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mytrip.Votes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VotesLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VotesLanguage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mytrip.Votes.VotesLanguage", typeof(VotesLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Vote.
        /// </summary>
        public static string add_new_vote {
            get {
                return ResourceManager.GetString("add_new_vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All languages.
        /// </summary>
        public static string all_languages {
            get {
                return ResourceManager.GetString("all_languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string answer {
            get {
                return ResourceManager.GetString("answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer can not be empty..
        /// </summary>
        public static string answer_can_not_be_empty {
            get {
                return ResourceManager.GetString("answer_can_not_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string are_you_sure {
            get {
                return ResourceManager.GetString("are_you_sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose number of answers:.
        /// </summary>
        public static string choose_number_of_answers {
            get {
                return ResourceManager.GetString("choose_number_of_answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close date.
        /// </summary>
        public static string close_date {
            get {
                return ResourceManager.GetString("close_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display in all languages.
        /// </summary>
        public static string display_in_all_languages {
            get {
                return ResourceManager.GetString("display_in_all_languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Vote.
        /// </summary>
        public static string edit_vote {
            get {
                return ResourceManager.GetString("edit_vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make active.
        /// </summary>
        public static string make_active {
            get {
                return ResourceManager.GetString("make_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Votes for accardion.
        /// </summary>
        public static string namevotes {
            get {
                return ResourceManager.GetString("namevotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be null or empty..
        /// </summary>
        public static string nullvalue {
            get {
                return ResourceManager.GetString("nullvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as unactive.
        /// </summary>
        public static string off_vote {
            get {
                return ResourceManager.GetString("off_vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as active.
        /// </summary>
        public static string on_vote {
            get {
                return ResourceManager.GetString("on_vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only for registered users.
        /// </summary>
        public static string only_for_registered_users {
            get {
                return ResourceManager.GetString("only_for_registered_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Vote.
        /// </summary>
        public static string our_vote {
            get {
                return ResourceManager.GetString("our_vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question should be longer than 3 characters..
        /// </summary>
        public static string question_lenght {
            get {
                return ResourceManager.GetString("question_lenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question (max lenght 256 chars):.
        /// </summary>
        public static string question_max_lenght {
            get {
                return ResourceManager.GetString("question_max_lenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string results {
            get {
                return ResourceManager.GetString("results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total responses:.
        /// </summary>
        public static string total_responses {
            get {
                return ResourceManager.GetString("total_responses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Votes..
        /// </summary>
        public static string unlockvotes {
            get {
                return ResourceManager.GetString("unlockvotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote.
        /// </summary>
        public static string vote {
            get {
                return ResourceManager.GetString("vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votes Manager.
        /// </summary>
        public static string votes_manager {
            get {
                return ResourceManager.GetString("votes_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votes Setting.
        /// </summary>
        public static string votessetting {
            get {
                return ResourceManager.GetString("votessetting", resourceCulture);
            }
        }
    }
}
