//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mytrip.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CoreLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreLanguage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mytrip.Core.CoreLanguage", typeof(CoreLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha is entered with errors..
        /// </summary>
        public static string account_error_captcha {
            get {
                return ResourceManager.GetString("account_error_captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password are required to be a minimum of {0} characters in length..
        /// </summary>
        public static string account_error_password {
            get {
                return ResourceManager.GetString("account_error_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is entered with errors..
        /// </summary>
        public static string account_error_username {
            get {
                return ResourceManager.GetString("account_error_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        public static string account_information {
            get {
                return ResourceManager.GetString("account_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail are required to be a maximum of 50 characters in length..
        /// </summary>
        public static string account_max_length_email {
            get {
                return ResourceManager.GetString("account_max_length_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password are required to be a maximum of 50 characters in length..
        /// </summary>
        public static string account_max_length_password {
            get {
                return ResourceManager.GetString("account_max_length_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name are required to be a maximum of 50 characters in length..
        /// </summary>
        public static string account_max_length_username {
            get {
                return ResourceManager.GetString("account_max_length_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha cannot be null or empty..
        /// </summary>
        public static string account_null_captcha {
            get {
                return ResourceManager.GetString("account_null_captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail cannot be null or empty..
        /// </summary>
        public static string account_null_email {
            get {
                return ResourceManager.GetString("account_null_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be null or empty..
        /// </summary>
        public static string account_null_password {
            get {
                return ResourceManager.GetString("account_null_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name cannot be null or empty..
        /// </summary>
        public static string account_null_username {
            get {
                return ResourceManager.GetString("account_null_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add role.
        /// </summary>
        public static string add_role {
            get {
                return ResourceManager.GetString("add_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User to Role.
        /// </summary>
        public static string add_user_to_role {
            get {
                return ResourceManager.GetString("add_user_to_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All roles.
        /// </summary>
        public static string all_roles {
            get {
                return ResourceManager.GetString("all_roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All users.
        /// </summary>
        public static string all_users {
            get {
                return ResourceManager.GetString("all_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string are_you_sure {
            get {
                return ResourceManager.GetString("are_you_sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string back_to_list {
            get {
                return ResourceManager.GetString("back_to_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte.
        /// </summary>
        public static string bytes {
            get {
                return ResourceManager.GetString("bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha.
        /// </summary>
        public static string Captcha {
            get {
                return ResourceManager.GetString("Captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change date.
        /// </summary>
        public static string change_date {
            get {
                return ResourceManager.GetString("change_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string change_password {
            get {
                return ResourceManager.GetString("change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfully..
        /// </summary>
        public static string change_password_success {
            get {
                return ResourceManager.GetString("change_password_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the form below to change your password..
        /// </summary>
        public static string change_password_text_first {
            get {
                return ResourceManager.GetString("change_password_text_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New passwords are required to be a minimum of {0} characters in length..
        /// </summary>
        public static string change_password_text_last {
            get {
                return ResourceManager.GetString("change_password_text_last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose new name.
        /// </summary>
        public static string choose_new_name {
            get {
                return ResourceManager.GetString("choose_new_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a role.
        /// </summary>
        public static string choose_role {
            get {
                return ResourceManager.GetString("choose_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Account.
        /// </summary>
        public static string create_account {
            get {
                return ResourceManager.GetString("create_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new folder:.
        /// </summary>
        public static string create_new_folder {
            get {
                return ResourceManager.GetString("create_new_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string default_provider_error {
            get {
                return ResourceManager.GetString("default_provider_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate to project.
        /// </summary>
        public static string donate {
            get {
                return ResourceManager.GetString("donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error occurred while processing your request..
        /// </summary>
        public static string error_text {
            get {
                return ResourceManager.GetString("error_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string error1 {
            get {
                return ResourceManager.GetString("error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists. Please enter a different file..
        /// </summary>
        public static string file_dublicate_file {
            get {
                return ResourceManager.GetString("file_dublicate_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name folder already exists. Please enter a different name folder..
        /// </summary>
        public static string file_dublicate_name {
            get {
                return ResourceManager.GetString("file_dublicate_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files Manager.
        /// </summary>
        public static string file_manager {
            get {
                return ResourceManager.GetString("file_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name folder are required to be a maximum of 30 characters in length..
        /// </summary>
        public static string file_max_name {
            get {
                return ResourceManager.GetString("file_max_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File cannot be null or empty..
        /// </summary>
        public static string file_null_file {
            get {
                return ResourceManager.GetString("file_null_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name folder cannot be null or empty..
        /// </summary>
        public static string file_null_name {
            get {
                return ResourceManager.GetString("file_null_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Approved.
        /// </summary>
        public static string IsApproved {
            get {
                return ResourceManager.GetString("IsApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Activity Date.
        /// </summary>
        public static string LastActivityDate {
            get {
                return ResourceManager.GetString("LastActivityDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Login Date.
        /// </summary>
        public static string LastLoginDate {
            get {
                return ResourceManager.GetString("LastLoginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Password Changed Date.
        /// </summary>
        public static string LastPasswordChangedDate {
            get {
                return ResourceManager.GetString("LastPasswordChangedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string logoff {
            get {
                return ResourceManager.GetString("logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On.
        /// </summary>
        public static string logon {
            get {
                return ResourceManager.GetString("logon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is entered with errors..
        /// </summary>
        public static string logon_error_password {
            get {
                return ResourceManager.GetString("logon_error_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your username and password. .
        /// </summary>
        public static string logon_text {
            get {
                return ResourceManager.GetString("logon_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  if you don&apos;t have an account..
        /// </summary>
        public static string logon_text1 {
            get {
                return ResourceManager.GetString("logon_text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string my_profile {
            get {
                return ResourceManager.GetString("my_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A username for that e-mail address already exists. Please enter a different e-mail address..
        /// </summary>
        public static string register_duplicate_email {
            get {
                return ResourceManager.GetString("register_duplicate_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name already exists. Please enter a different user name..
        /// </summary>
        public static string register_duplicate_username {
            get {
                return ResourceManager.GetString("register_duplicate_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail address provided is invalid. Please check the value and try again..
        /// </summary>
        public static string register_error_email {
            get {
                return ResourceManager.GetString("register_error_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string register_password_confurmpassword {
            get {
                return ResourceManager.GetString("register_password_confurmpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the form below to create a new account..
        /// </summary>
        public static string register_text_first {
            get {
                return ResourceManager.GetString("register_text_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords are required to be a minimum of {0} characters in length..
        /// </summary>
        public static string register_text_last {
            get {
                return ResourceManager.GetString("register_text_last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string rename {
            get {
                return ResourceManager.GetString("rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename file or folder.
        /// </summary>
        public static string rename_file_or_folder {
            get {
                return ResourceManager.GetString("rename_file_or_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already belong to this role. Please choose another one..
        /// </summary>
        public static string role_in_user {
            get {
                return ResourceManager.GetString("role_in_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Information.
        /// </summary>
        public static string role_information {
            get {
                return ResourceManager.GetString("role_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role cannot be null or empty..
        /// </summary>
        public static string role_null {
            get {
                return ResourceManager.GetString("role_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name already exists. Please enter a different role name..
        /// </summary>
        public static string rolename_duplicate {
            get {
                return ResourceManager.GetString("rolename_duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name are required to be a maximum of 15 characters in length..
        /// </summary>
        public static string rolename_max_length {
            get {
                return ResourceManager.GetString("rolename_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name cannot be null or empty..
        /// </summary>
        public static string rolename_null {
            get {
                return ResourceManager.GetString("rolename_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search are required to be a maximum of 50 characters in length..
        /// </summary>
        public static string search_max_length {
            get {
                return ResourceManager.GetString("search_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search cannot be null or empty..
        /// </summary>
        public static string search_null {
            get {
                return ResourceManager.GetString("search_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search role.
        /// </summary>
        public static string search_role {
            get {
                return ResourceManager.GetString("search_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search user.
        /// </summary>
        public static string search_user {
            get {
                return ResourceManager.GetString("search_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file for upload..
        /// </summary>
        public static string select_file_upload {
            get {
                return ResourceManager.GetString("select_file_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string size {
            get {
                return ResourceManager.GetString("size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string theme {
            get {
                return ResourceManager.GetString("theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string upload {
            get {
                return ResourceManager.GetString("upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file:.
        /// </summary>
        public static string upload_file {
            get {
                return ResourceManager.GetString("upload_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users and Files.
        /// </summary>
        public static string user_file {
            get {
                return ResourceManager.GetString("user_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user in role.
        /// </summary>
        public static string user_in_role {
            get {
                return ResourceManager.GetString("user_in_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is approved.
        /// </summary>
        public static string user_is_approved {
            get {
                return ResourceManager.GetString("user_is_approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is not approved.
        /// </summary>
        public static string user_is_not_approved {
            get {
                return ResourceManager.GetString("user_is_not_approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users manager.
        /// </summary>
        public static string user_manager {
            get {
                return ResourceManager.GetString("user_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Count.
        /// </summary>
        public static string UserCount {
            get {
                return ResourceManager.GetString("UserCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User IP.
        /// </summary>
        public static string UserIP {
            get {
                return ResourceManager.GetString("UserIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome {0}!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
