//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mtm.Store.Files {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebPages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebPages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mtm.Store.Files.WebPages", typeof(WebPages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model mtm.Store.Models.CartModel
        ///@{ 
        ///    /* Copyright © 2009 - 2010 Oleg Stuhin &amp; Rostislav Haitovich 
        ///       To learn more about Mytrip.Mvc visit  
        ///       http://mytripmvc.net  http://mytripmvc.codeplex.com 
        ///       mytripmvc@gmail.com
        ///       license: Microsoft Public License (Ms-PL) */ 
        ///}
        ///@{
        ///    ViewBag.Title = Html.MytripPageTitle(Model.title, &quot;/&quot;);
        ///    ViewBag.Keywords = Html.MytripPageTitle(Model.title, &quot;,&quot;);
        ///    ViewBag.Description = Html.MytripPageTitle(Model.title, &quot;,&quot;);
        ///}
        ///@section scriptlink{
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model mtm.Store.Models.CreateProductXmlModel
        ///@{ 
        ///    /* Copyright © 2009 - 2010 Oleg Stuhin &amp; Rostislav Haitovich 
        ///       To learn more about Mytrip.Mvc visit  
        ///       http://mytripmvc.net  http://mytripmvc.codeplex.com 
        ///       mytripmvc@gmail.com
        ///       license: Microsoft Public License (Ms-PL) */ 
        ///}
        ///@{
        ///    ViewBag.Title = Html.MytripPageTitle(StoreLanguage.uploadproductxml, &quot;/&quot;);
        ///    ViewBag.Keywords=Html.MytripPageTitle(StoreLanguage.uploadproductxml, &quot;,&quot;);
        ///    ViewBag.Description=Html.MytripPageTitle [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateProductXml {
            get {
                return ResourceManager.GetString("CreateProductXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model mtm.Store.Models.CreateSaleModel
        ///@{ 
        ///    /* Copyright © 2009 - 2010 Oleg Stuhin &amp; Rostislav Haitovich 
        ///       To learn more about Mytrip.Mvc visit  
        ///       http://mytripmvc.net  http://mytripmvc.codeplex.com 
        ///       mytripmvc@gmail.com
        ///       license: Microsoft Public License (Ms-PL) */ 
        ///}
        ///@{
        ///    ViewBag.Title = Html.MytripPageTitle(StoreLanguage.createsale, &quot;/&quot;);
        ///    ViewBag.Keywords=Html.MytripPageTitle(StoreLanguage.createsale, &quot;,&quot;);
        ///    ViewBag.Description=Html.MytripPageTitle(StoreLanguage.cre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateSale {
            get {
                return ResourceManager.GetString("CreateSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model mtm.Store.Models.EditorCategoryModel
        ///@{ 
        ///    /* Copyright © 2009 - 2010 Oleg Stuhin &amp; Rostislav Haitovich 
        ///       To learn more about Mytrip.Mvc visit  
        ///       http://mytripmvc.net  http://mytripmvc.codeplex.com 
        ///       mytripmvc@gmail.com
        ///       license: Microsoft Public License (Ms-PL) */ 
        ///}
        ///@{
        ///    ViewBag.Title = Html.MytripPageTitle(Model.PageTitle, &quot;/&quot;);
        ///    ViewBag.Keywords=Html.MytripPageTitle(Model.PageTitle, &quot;,&quot;);
        ///    ViewBag.Description=Html.MytripPageTitle(Model.PageTitle, &quot;,&quot;);
        ///}
        ///@sec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EditorCategory {
            get {
                return ResourceManager.GetString("EditorCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model mtm.Store.Models.EditorProductModel
        ///@{ 
        ///    /* Copyright © 2009 - 2010 Oleg Stuhin &amp; Rostislav Haitovich 
        ///       To learn more about Mytrip.Mvc visit  
        ///       http://mytripmvc.net  http://mytripmvc.codeplex.com 
        ///       mytripmvc@gmail.com
        ///       license: Microsoft Public License (Ms-PL) */ 
        ///}
        ///@{
        ///    ViewBag.Title = Html.MytripPageTitle(Model.PageTitle, &quot;/&quot;);
        ///    ViewBag.Keywords = Html.MytripPageTitle(Model.PageTitle, &quot;,&quot;);
        ///    ViewBag.Description = Html.MytripPageTitle(Model.PageTitle, &quot;,&quot;);
        ///}
        ///@ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EditorProduct {
            get {
                return ResourceManager.GetString("EditorProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model mtm.Store.Models.DepartmentModel
        ///@{ 
        ///    /* Copyright © 2009 - 2010 Oleg Stuhin &amp; Rostislav Haitovich
        ///       To learn more about Mytrip.Mvc visit
        ///       http://mytripmvc.net  http://mytripmvc.codeplex.com
        ///       mytripmvc@gmail.com
        ///       license: Microsoft Public License (Ms-PL) */
        ///}
        ///@{
        ///    ViewBag.Title = Html.MytripPageTitle(Model.titleDepartmentModel.title, &quot;/&quot;);
        ///    ViewBag.Keywords = Html.MytripPageTitle(Model.titleDepartmentModel.title, &quot;,&quot;);
        ///    ViewBag.Description = Html.MytripPageTitle(Mo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{ 
        ///    /* Copyright © 2009 - 2010 Oleg Stuhin &amp; Rostislav Haitovich 
        ///       To learn more about Mytrip.Mvc visit  
        ///       http://mytripmvc.net  http://mytripmvc.codeplex.com 
        ///       mytripmvc@gmail.com
        ///       license: Microsoft Public License (Ms-PL) */ 
        ///}
        ///@{
        ///    ViewBag.Title = Html.MytripPageTitle(StoreLanguage.manager, &quot;/&quot;);
        ///    ViewBag.Keywords=Html.MytripPageTitle(StoreLanguage.manager, &quot;,&quot;);
        ///    ViewBag.Description=Html.MytripPageTitle(StoreLanguage.manager, &quot;,&quot;);
        ///}
        ///@section content{
        ///&lt;h1 class=&quot;t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{ 
        ///    /* Copyright © 2009 - 2010 Oleg Stuhin &amp; Rostislav Haitovich 
        ///       To learn more about Mytrip.Mvc visit  
        ///       http://mytripmvc.net  http://mytripmvc.codeplex.com 
        ///       mytripmvc@gmail.com
        ///       license: Microsoft Public License (Ms-PL) */ 
        ///}
        ///@{
        ///    ViewBag.Title = Html.MytripPageTitle(StoreLanguage.managerorders, &quot;/&quot;);
        ///    ViewBag.Keywords=Html.MytripPageTitle(StoreLanguage.managerorders, &quot;,&quot;);
        ///    ViewBag.Description=Html.MytripPageTitle(StoreLanguage.managerorders, &quot;,&quot;);
        ///}
        ///@section scri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ManagerOrders {
            get {
                return ResourceManager.GetString("ManagerOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model mtm.Store.Models.OrderDetailsModel
        ///@{ 
        ///    /* Copyright © 2009 - 2010 Oleg Stuhin &amp; Rostislav Haitovich 
        ///       To learn more about Mytrip.Mvc visit  
        ///       http://mytripmvc.net  http://mytripmvc.codeplex.com 
        ///       mytripmvc@gmail.com
        ///       license: Microsoft Public License (Ms-PL) */ 
        ///}
        ///@{
        ///    ViewBag.Title = Html.MytripPageTitle(string.Format(StoreLanguage.orderdetailstitle,Model.id), &quot;/&quot;);
        ///    ViewBag.Keywords=Html.MytripPageTitle(string.Format(StoreLanguage.orderdetailstitle,Model.id), &quot;, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OrderDetails {
            get {
                return ResourceManager.GetString("OrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model mtm.Store.Models.SettingStorelModel
        ///@{ 
        ///    /* Copyright © 2009 - 2010 Oleg Stuhin &amp; Rostislav Haitovich 
        ///       To learn more about Mytrip.Mvc visit  
        ///       http://mytripmvc.net  http://mytripmvc.codeplex.com 
        ///       mytripmvc@gmail.com
        ///       license: Microsoft Public License (Ms-PL) */ 
        ///}
        ///@{
        ///    ViewBag.Title = Html.MytripPageTitle(StoreLanguage.storeSetting, &quot;/&quot;);
        ///    ViewBag.Keywords=Html.MytripPageTitle(StoreLanguage.storeSetting, &quot;,&quot;);
        ///    ViewBag.Description=Html.MytripPageTitle(StoreLangu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model mtm.Store.Models.ProductModel
        ///@{ 
        ///    /* Copyright © 2009 - 2010 Oleg Stuhin &amp; Rostislav Haitovich 
        ///       To learn more about Mytrip.Mvc visit  
        ///       http://mytripmvc.net  http://mytripmvc.codeplex.com 
        ///       mytripmvc@gmail.com
        ///       license: Microsoft Public License (Ms-PL) */ 
        ///}
        ///@{
        ///    ViewBag.Title = Html.MytripPageTitle(&quot;&quot;, &quot;/&quot;);
        ///    ViewBag.Keywords=Html.MytripPageTitle(&quot;&quot;, &quot;,&quot;);
        ///    ViewBag.Description=Html.MytripPageTitle(&quot;&quot;, &quot;,&quot;);
        ///}
        ///@section scriptlink{
        ///@Html.ScriptLink(&quot;MicrosoftA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///
        ///&lt;configuration&gt;
        ///   &lt;system.web.webPages.razor&gt;
        ///       &lt;pages pageBaseType=&quot;System.Web.Mvc.WebViewPage&quot;&gt;        
        ///            &lt;namespaces&gt;
        ///                &lt;add namespace=&quot;mtm.Store&quot; /&gt;
        ///                &lt;add namespace=&quot;mtm.Store.Helpers&quot; /&gt;
        ///            &lt;/namespaces&gt;
        ///        &lt;/pages&gt;
        ///    &lt;/system.web.webPages.razor&gt;
        ///&lt;/configuration&gt;.
        /// </summary>
        internal static string Web {
            get {
                return ResourceManager.GetString("Web", resourceCulture);
            }
        }
    }
}
