//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Mytrip.Store.Repository.DataEntities
{
    public partial class mytrip_storedepartment
    {
        #region Primitive Properties
    
        public virtual int DepartmentId
        {
            get;
            set;
        }
    
        public virtual string Title
        {
            get;
            set;
        }
    
        public virtual string Path
        {
            get;
            set;
        }
    
        public virtual string Culture
        {
            get;
            set;
        }
    
        public virtual bool AllCulture
        {
            get;
            set;
        }
    
        public virtual string UserName
        {
            get;
            set;
        }
    
        public virtual System.DateTime CreationDate
        {
            get;
            set;
        }
    
        public virtual string Body
        {
            get;
            set;
        }
    
        public virtual string Image
        {
            get;
            set;
        }
    
        public virtual int SubDepartmentId
        {
            get { return _subDepartmentId; }
            set
            {
                if (_subDepartmentId != value)
                {
                    if (mytrip_storedepartment2 != null && mytrip_storedepartment2.DepartmentId != value)
                    {
                        mytrip_storedepartment2 = null;
                    }
                    _subDepartmentId = value;
                }
            }
        }
        private int _subDepartmentId;

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<mytrip_storedepartment> mytrip_storedepartment1
        {
            get
            {
                if (_mytrip_storedepartment1 == null)
                {
                    var newCollection = new FixupCollection<mytrip_storedepartment>();
                    newCollection.CollectionChanged += Fixupmytrip_storedepartment1;
                    _mytrip_storedepartment1 = newCollection;
                }
                return _mytrip_storedepartment1;
            }
            set
            {
                if (!ReferenceEquals(_mytrip_storedepartment1, value))
                {
                    var previousValue = _mytrip_storedepartment1 as FixupCollection<mytrip_storedepartment>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupmytrip_storedepartment1;
                    }
                    _mytrip_storedepartment1 = value;
                    var newValue = value as FixupCollection<mytrip_storedepartment>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupmytrip_storedepartment1;
                    }
                }
            }
        }
        private ICollection<mytrip_storedepartment> _mytrip_storedepartment1;
    
        public virtual mytrip_storedepartment mytrip_storedepartment2
        {
            get { return _mytrip_storedepartment2; }
            set
            {
                if (!ReferenceEquals(_mytrip_storedepartment2, value))
                {
                    var previousValue = _mytrip_storedepartment2;
                    _mytrip_storedepartment2 = value;
                    Fixupmytrip_storedepartment2(previousValue);
                }
            }
        }
        private mytrip_storedepartment _mytrip_storedepartment2;
    
        public virtual ICollection<mytrip_storeproduct> mytrip_storeproduct
        {
            get
            {
                if (_mytrip_storeproduct == null)
                {
                    var newCollection = new FixupCollection<mytrip_storeproduct>();
                    newCollection.CollectionChanged += Fixupmytrip_storeproduct;
                    _mytrip_storeproduct = newCollection;
                }
                return _mytrip_storeproduct;
            }
            set
            {
                if (!ReferenceEquals(_mytrip_storeproduct, value))
                {
                    var previousValue = _mytrip_storeproduct as FixupCollection<mytrip_storeproduct>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupmytrip_storeproduct;
                    }
                    _mytrip_storeproduct = value;
                    var newValue = value as FixupCollection<mytrip_storeproduct>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupmytrip_storeproduct;
                    }
                }
            }
        }
        private ICollection<mytrip_storeproduct> _mytrip_storeproduct;

        #endregion
        #region Association Fixup
    
        private void Fixupmytrip_storedepartment2(mytrip_storedepartment previousValue)
        {
            if (previousValue != null && previousValue.mytrip_storedepartment1.Contains(this))
            {
                previousValue.mytrip_storedepartment1.Remove(this);
            }
    
            if (mytrip_storedepartment2 != null)
            {
                if (!mytrip_storedepartment2.mytrip_storedepartment1.Contains(this))
                {
                    mytrip_storedepartment2.mytrip_storedepartment1.Add(this);
                }
                if (SubDepartmentId != mytrip_storedepartment2.DepartmentId)
                {
                    SubDepartmentId = mytrip_storedepartment2.DepartmentId;
                }
            }
        }
    
        private void Fixupmytrip_storedepartment1(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (mytrip_storedepartment item in e.NewItems)
                {
                    item.mytrip_storedepartment2 = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (mytrip_storedepartment item in e.OldItems)
                {
                    if (ReferenceEquals(item.mytrip_storedepartment2, this))
                    {
                        item.mytrip_storedepartment2 = null;
                    }
                }
            }
        }
    
        private void Fixupmytrip_storeproduct(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (mytrip_storeproduct item in e.NewItems)
                {
                    item.mytrip_storedepartment = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (mytrip_storeproduct item in e.OldItems)
                {
                    if (ReferenceEquals(item.mytrip_storedepartment, this))
                    {
                        item.mytrip_storedepartment = null;
                    }
                }
            }
        }

        #endregion
    }
}
