//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Mytrip.Votes.Repository.DataEntities
{
    public partial class mytrip_votesanswer
    {
        #region Primitive Properties
    
        public virtual int AnswerId
        {
            get;
            set;
        }
    
        public virtual int QuestionId
        {
            get { return _questionId; }
            set
            {
                if (_questionId != value)
                {
                    if (mytrip_votesquestion != null && mytrip_votesquestion.QuestionId != value)
                    {
                        mytrip_votesquestion = null;
                    }
                    _questionId = value;
                }
            }
        }
        private int _questionId;
    
        public virtual string Answer
        {
            get;
            set;
        }
    
        public virtual int TotalVotes
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual mytrip_votesquestion mytrip_votesquestion
        {
            get { return _mytrip_votesquestion; }
            set
            {
                if (!ReferenceEquals(_mytrip_votesquestion, value))
                {
                    var previousValue = _mytrip_votesquestion;
                    _mytrip_votesquestion = value;
                    Fixupmytrip_votesquestion(previousValue);
                }
            }
        }
        private mytrip_votesquestion _mytrip_votesquestion;

        #endregion
        #region Association Fixup
    
        private void Fixupmytrip_votesquestion(mytrip_votesquestion previousValue)
        {
            if (previousValue != null && previousValue.mytrip_votesanswer.Contains(this))
            {
                previousValue.mytrip_votesanswer.Remove(this);
            }
    
            if (mytrip_votesquestion != null)
            {
                if (!mytrip_votesquestion.mytrip_votesanswer.Contains(this))
                {
                    mytrip_votesquestion.mytrip_votesanswer.Add(this);
                }
                if (QuestionId != mytrip_votesquestion.QuestionId)
                {
                    QuestionId = mytrip_votesquestion.QuestionId;
                }
            }
        }

        #endregion
    }
}
