//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mtm.Weather {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WeatherLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WeatherLanguage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mtm.Weather.WeatherLanguage", typeof(WeatherLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Weather.
        /// </summary>
        public static string add_Weather {
            get {
                return ResourceManager.GetString("add_Weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All languages.
        /// </summary>
        public static string all_languages {
            get {
                return ResourceManager.GetString("all_languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all culture.
        /// </summary>
        public static string AllCulture {
            get {
                return ResourceManager.GetString("AllCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string are_you_sure {
            get {
                return ResourceManager.GetString("are_you_sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by day.
        /// </summary>
        public static string day {
            get {
                return ResourceManager.GetString("day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Weather.
        /// </summary>
        public static string edit_Weather {
            get {
                return ResourceManager.GetString("edit_Weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather name for sidebar.
        /// </summary>
        public static string nameWeather {
            get {
                return ResourceManager.GetString("nameWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at night.
        /// </summary>
        public static string night {
            get {
                return ResourceManager.GetString("night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required information is missing..
        /// </summary>
        public static string nullvalue {
            get {
                return ResourceManager.GetString("nullvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Weather.
        /// </summary>
        public static string unlockWeather {
            get {
                return ResourceManager.GetString("unlockWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url Xml.
        /// </summary>
        public static string UrlXml {
            get {
                return ResourceManager.GetString("UrlXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible Informer.
        /// </summary>
        public static string VisibleInformer {
            get {
                return ResourceManager.GetString("VisibleInformer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather Manager.
        /// </summary>
        public static string Weather_manager {
            get {
                return ResourceManager.GetString("Weather_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather Setting.
        /// </summary>
        public static string Weathersetting {
            get {
                return ResourceManager.GetString("Weathersetting", resourceCulture);
            }
        }
    }
}
