//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace mtm.Core.Repository.DataEntities
{
    public partial class mytrip_corestatistic
    {
        #region Primitive Properties
    
        public virtual int StatisticId
        {
            get;
            set;
        }
    
        public virtual string UserIP
        {
            get;
            set;
        }
    
        public virtual System.DateTime Date
        {
            get;
            set;
        }
    
        public virtual string Page
        {
            get;
            set;
        }
    
        public virtual string Referrer
        {
            get;
            set;
        }
    
        public virtual string Browser
        {
            get;
            set;
        }
    
        public virtual string OS
        {
            get;
            set;
        }
    
        public virtual int CityId
        {
            get { return _cityId; }
            set
            {
                if (_cityId != value)
                {
                    if (mytrip_geocity != null && mytrip_geocity.CityId != value)
                    {
                        mytrip_geocity = null;
                    }
                    _cityId = value;
                }
            }
        }
        private int _cityId;
    
        public virtual int UserCount
        {
            get;
            set;
        }
    
        public virtual int ViewCount
        {
            get;
            set;
        }
    
        public virtual bool Day
        {
            get;
            set;
        }
    
        public virtual bool Month
        {
            get;
            set;
        }
    
        public virtual bool Year
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Time
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual mytrip_geocity mytrip_geocity
        {
            get { return _mytrip_geocity; }
            set
            {
                if (!ReferenceEquals(_mytrip_geocity, value))
                {
                    var previousValue = _mytrip_geocity;
                    _mytrip_geocity = value;
                    Fixupmytrip_geocity(previousValue);
                }
            }
        }
        private mytrip_geocity _mytrip_geocity;

        #endregion
        #region Association Fixup
    
        private void Fixupmytrip_geocity(mytrip_geocity previousValue)
        {
            if (previousValue != null && previousValue.mytrip_corestatistic.Contains(this))
            {
                previousValue.mytrip_corestatistic.Remove(this);
            }
    
            if (mytrip_geocity != null)
            {
                if (!mytrip_geocity.mytrip_corestatistic.Contains(this))
                {
                    mytrip_geocity.mytrip_corestatistic.Add(this);
                }
                if (CityId != mytrip_geocity.CityId)
                {
                    CityId = mytrip_geocity.CityId;
                }
            }
        }

        #endregion
    }
}
