//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace mtm.Core.Repository.DataEntities
{
    public partial class mytrip_usersprofile
    {
        #region Primitive Properties
    
        public virtual string UserId
        {
            get { return _userId; }
            set
            {
                if (_userId != value)
                {
                    if (mytrip_users != null && mytrip_users.UserId != value)
                    {
                        mytrip_users = null;
                    }
                    _userId = value;
                }
            }
        }
        private string _userId;
    
        public virtual string FirstName
        {
            get;
            set;
        }
    
        public virtual string LastName
        {
            get;
            set;
        }
    
        public virtual string Phone
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> Longitude
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> Latitude
        {
            get;
            set;
        }
    
        public virtual string Site
        {
            get;
            set;
        }
    
        public virtual string Description
        {
            get;
            set;
        }
    
        public virtual string icq
        {
            get;
            set;
        }
    
        public virtual string skype
        {
            get;
            set;
        }
    
        public virtual int CityId
        {
            get { return _cityId; }
            set
            {
                if (_cityId != value)
                {
                    if (mytrip_geocity != null && mytrip_geocity.CityId != value)
                    {
                        mytrip_geocity = null;
                    }
                    _cityId = value;
                }
            }
        }
        private int _cityId;
    
        public virtual bool ProfileClose
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual mytrip_geocity mytrip_geocity
        {
            get { return _mytrip_geocity; }
            set
            {
                if (!ReferenceEquals(_mytrip_geocity, value))
                {
                    var previousValue = _mytrip_geocity;
                    _mytrip_geocity = value;
                    Fixupmytrip_geocity(previousValue);
                }
            }
        }
        private mytrip_geocity _mytrip_geocity;
    
        public virtual mytrip_users mytrip_users
        {
            get { return _mytrip_users; }
            set
            {
                if (!ReferenceEquals(_mytrip_users, value))
                {
                    var previousValue = _mytrip_users;
                    _mytrip_users = value;
                    Fixupmytrip_users(previousValue);
                }
            }
        }
        private mytrip_users _mytrip_users;

        #endregion
        #region Association Fixup
    
        private void Fixupmytrip_geocity(mytrip_geocity previousValue)
        {
            if (previousValue != null && previousValue.mytrip_usersprofile.Contains(this))
            {
                previousValue.mytrip_usersprofile.Remove(this);
            }
    
            if (mytrip_geocity != null)
            {
                if (!mytrip_geocity.mytrip_usersprofile.Contains(this))
                {
                    mytrip_geocity.mytrip_usersprofile.Add(this);
                }
                if (CityId != mytrip_geocity.CityId)
                {
                    CityId = mytrip_geocity.CityId;
                }
            }
        }
    
        private void Fixupmytrip_users(mytrip_users previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.mytrip_usersprofile, this))
            {
                previousValue.mytrip_usersprofile = null;
            }
    
            if (mytrip_users != null)
            {
                mytrip_users.mytrip_usersprofile = this;
                if (UserId != mytrip_users.UserId)
                {
                    UserId = mytrip_users.UserId;
                }
            }
        }

        #endregion
    }
}
