//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace mtm.Core.Repository.DataEntities
{
    public partial class Entities : ObjectContext
    {
        public const string ConnectionString = "name=Entities";
        public const string ContainerName = "Entities";
    
        #region Constructors
    
        public Entities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
        }
    
        public Entities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
        }
    
        public Entities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<mytrip_users> mytrip_users
        {
            get { return _mytrip_users  ?? (_mytrip_users = CreateObjectSet<mytrip_users>("mytrip_users")); }
        }
        private ObjectSet<mytrip_users> _mytrip_users;
    
        public ObjectSet<mytrip_usersmembership> mytrip_usersmembership
        {
            get { return _mytrip_usersmembership  ?? (_mytrip_usersmembership = CreateObjectSet<mytrip_usersmembership>("mytrip_usersmembership")); }
        }
        private ObjectSet<mytrip_usersmembership> _mytrip_usersmembership;
    
        public ObjectSet<mytrip_usersroles> mytrip_usersroles
        {
            get { return _mytrip_usersroles  ?? (_mytrip_usersroles = CreateObjectSet<mytrip_usersroles>("mytrip_usersroles")); }
        }
        private ObjectSet<mytrip_usersroles> _mytrip_usersroles;
    
        public ObjectSet<mytrip_corepages> mytrip_corepages
        {
            get { return _mytrip_corepages  ?? (_mytrip_corepages = CreateObjectSet<mytrip_corepages>("mytrip_corepages")); }
        }
        private ObjectSet<mytrip_corepages> _mytrip_corepages;
    
        public ObjectSet<mytrip_geocity> mytrip_geocity
        {
            get { return _mytrip_geocity  ?? (_mytrip_geocity = CreateObjectSet<mytrip_geocity>("mytrip_geocity")); }
        }
        private ObjectSet<mytrip_geocity> _mytrip_geocity;
    
        public ObjectSet<mytrip_geocountry> mytrip_geocountry
        {
            get { return _mytrip_geocountry  ?? (_mytrip_geocountry = CreateObjectSet<mytrip_geocountry>("mytrip_geocountry")); }
        }
        private ObjectSet<mytrip_geocountry> _mytrip_geocountry;
    
        public ObjectSet<mytrip_georegion> mytrip_georegion
        {
            get { return _mytrip_georegion  ?? (_mytrip_georegion = CreateObjectSet<mytrip_georegion>("mytrip_georegion")); }
        }
        private ObjectSet<mytrip_georegion> _mytrip_georegion;
    
        public ObjectSet<mytrip_corestatistic> mytrip_corestatistic
        {
            get { return _mytrip_corestatistic  ?? (_mytrip_corestatistic = CreateObjectSet<mytrip_corestatistic>("mytrip_corestatistic")); }
        }
        private ObjectSet<mytrip_corestatistic> _mytrip_corestatistic;
    
        public ObjectSet<mytrip_usersprofile> mytrip_usersprofile
        {
            get { return _mytrip_usersprofile  ?? (_mytrip_usersprofile = CreateObjectSet<mytrip_usersprofile>("mytrip_usersprofile")); }
        }
        private ObjectSet<mytrip_usersprofile> _mytrip_usersprofile;

        #endregion
    }
}
