using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Mytrip.Mvc.Interface;
using Mytrip.Mvc.Install;

namespace Mytrip.Store
{
    public class StoreCreateDataBase : ICreateDataBase
    {
        public void CreateAndDeleteDataBase(bool create)
        {
            CreateDataBase.CreateDataBaseMSSQL(scriptMSSQL(), deleteScriptMSSQL(), create);
            CreateDataBase.CreateDataBaseMYSQL(scriptMYSQL(), deleteScriptMYSQL(), create);
        }
        private string[] scriptMSSQL()
        {
            string[] result = {
           "IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[mytrip_storeseller]') AND type in (N'U'))",
           "BEGIN",
           "CREATE TABLE [dbo].[mytrip_storeseller](",
	       "[SellerId] [int] NOT NULL,",
	       "[Organization] [nvarchar](256) NULL,",
	       "[Address] [nvarchar](max) NULL,",
	       "[Phone] [nvarchar](256) NULL,",
	       "[Email] [nvarchar](256) NULL,",
	       "[OrganizationINN] [nvarchar](256) NULL,",
	       "[OrganizationKPP] [nvarchar](256) NULL,",
	       "[BankAccountSeller] [nvarchar](256) NULL,",
	       "[BankAccountBIK] [nvarchar](256) NULL,",
	       "[Bank] [nvarchar](256) NULL,",
	       "[BankAccount] [nvarchar](256) NULL,",
	       "[Director] [nvarchar](256) NULL,",
	       "[Accountant] [nvarchar](256) NULL,",
	       "[LiteNDS] [bit] NOT NULL,",
	       "[Culture] [nvarchar](50) NOT NULL,",
	       "[AllCulture] [bit] NOT NULL,",
           "CONSTRAINT [PK_mytrip_storeseller] PRIMARY KEY CLUSTERED", 
           "(",
	       "[SellerId] ASC",
           ")WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]",
           ") ON [PRIMARY]",
           "END",
           "IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[mytrip_storesale]') AND type in (N'U'))",
           "BEGIN",
           "CREATE TABLE [dbo].[mytrip_storesale](",
	       "[SaleId] [int] NOT NULL,",
	       "[Sale] [int] NOT NULL,",
	       "[Title] [nvarchar](256) NULL,",
	       "[CreationDate] [datetime] NOT NULL,",
	       "[CloseDate] [datetime] NOT NULL,",
	       "[UserName] [nvarchar](256) NULL,",
	       "[StartDate] [datetime] NOT NULL,",
	       "[ManagerName] [nvarchar](256) NOT NULL,",
           "CONSTRAINT [PK_mytrip_storesale] PRIMARY KEY CLUSTERED", 
           "(",
	       "[SaleId] ASC",
           ")WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]",
           ") ON [PRIMARY]",
           "END",
           "IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[mytrip_storeprofile]') AND type in (N'U'))",
           "BEGIN",
           "CREATE TABLE [dbo].[mytrip_storeprofile](",
	       "[ProfileId] [int] NOT NULL,",
	       "[UserName] [nvarchar](256) NOT NULL,",
	       "[UserEmail] [nvarchar](256) NOT NULL,",
	       "[Address] [nvarchar](max) NULL,",
	       "[Phone] [nvarchar](256) NULL,",
	       "[IsAnonym] [bit] NOT NULL,",
	       "[FirstName] [nvarchar](256) NOT NULL,",
	       "[LastName] [nvarchar](256) NULL,",
	       "[Organization] [nvarchar](256) NULL,",
	       "[OrganizationINN] [nvarchar](256) NULL,",
	       "[OrganizationKPP] [nvarchar](256) NULL,",
	       "[UserIP] [nvarchar](256) NOT NULL,",
           "CONSTRAINT [PK_mytrip_storeprofile] PRIMARY KEY CLUSTERED", 
           "(",
	       "[ProfileId] ASC",
           ")WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]",
           ") ON [PRIMARY]",
           "END",
           "IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[mytrip_storeorder]') AND type in (N'U'))",
           "BEGIN",
           "CREATE TABLE [dbo].[mytrip_storeorder](",
	       "[OrderId] [int] NOT NULL,",
	       "[Status] [int] NOT NULL,",
	       "[Culture] [nvarchar](256) NOT NULL,",
	       "[CreationDate] [datetime] NOT NULL,",
	       "[ManagerName] [nvarchar](256) NULL,",
	       "[Delivery] [decimal](18, 2) NOT NULL,",
	       "[PriceInWords] [nvarchar](256) NULL,",
	       "[NamberAccount] [int] NULL,",
           "[DateAccount] [datetime] NULL,",
	       "[AccountPage] [nvarchar](max) NULL,",
	       "[MoneyId] [nvarchar](50) NOT NULL,",
	       "[ProfileId] [int] NOT NULL,",
           "CONSTRAINT [PK_mytrip_storemanageorder] PRIMARY KEY CLUSTERED", 
           "(",
           "[OrderId] ASC",
           ")WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]",
           ") ON [PRIMARY]",
           "END",
           "IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[mytrip_storedepartment]') AND type in (N'U'))",
           "BEGIN",
           "CREATE TABLE [dbo].[mytrip_storedepartment](",
	       "[DepartmentId] [int] NOT NULL,",
	       "[Title] [nvarchar](256) NOT NULL,",
	       "[Path] [nvarchar](256) NOT NULL,",
	       "[Culture] [nvarchar](50) NOT NULL,",
	       "[AllCulture] [bit] NOT NULL,",
	       "[UserName] [nvarchar](100) NOT NULL,",
	       "[CreationDate] [datetime] NOT NULL,",
	       "[Body] [nvarchar](max) NULL,",
	       "[SubDepartmentId] [int] NOT NULL,",
           "[SaleId] [int] NOT NULL,",
           "CONSTRAINT [PK_mytrip_storedepartment] PRIMARY KEY CLUSTERED", 
           "(",
	       "[DepartmentId] ASC",
           ")WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]",
           ") ON [PRIMARY]",
           "END",
           "IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[mytrip_storeproducer]') AND type in (N'U'))",
           "BEGIN",
           "CREATE TABLE [dbo].[mytrip_storeproducer](",
	       "[ProducerId] [int] NOT NULL,",
	       "[Title] [nvarchar](256) NOT NULL,",
	       "[Body] [nvarchar](max) NULL,",
	       "[Path] [nvarchar](256) NOT NULL,",
	       "[Culture] [nvarchar](50) NOT NULL,",
	       "[AllCulture] [bit] NOT NULL,",
	       "[UserName] [nvarchar](100) NOT NULL,",
	       "[CreationDate] [datetime] NOT NULL,",
	       "[SaleId] [int] NOT NULL,",
           "CONSTRAINT [PK_mytrip_storeproducer] PRIMARY KEY CLUSTERED", 
           "(",
	       "[ProducerId] ASC",
           ")WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]",
           ") ON [PRIMARY]",
           "END",
           "IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[mytrip_storeproduct]') AND type in (N'U'))",
           "BEGIN",
           "CREATE TABLE [dbo].[mytrip_storeproduct](",
	       "[ProductId] [int] NOT NULL,",
	       "[DepartmentId] [int] NOT NULL,",
	       "[ProducerId] [int] NOT NULL,",
	       "[Title] [nvarchar](256) NOT NULL,",
	       "[Path] [nvarchar](256) NOT NULL,",
	       "[Details] [nvarchar](max) NULL,",
	       "[Body] [nvarchar](max) NULL,",
	       "[CreationDate] [datetime] NOT NULL,",
	       "[UserName] [nvarchar](100) NOT NULL,",
	       "[Culture] [nvarchar](50) NOT NULL,",
	       "[AllCulture] [bit] NOT NULL,",
	       "[Price] [decimal](18, 2) NOT NULL,",
 	       "[TotalVotes] [decimal](4, 2) NOT NULL,",
	       "[TotalCount] [int] NOT NULL,",
	       "[ViewPrice] [bit] NOT NULL,",
	       "[ViewVotes] [bit] NOT NULL,",
	       "[ViewCount] [bit] NOT NULL,",
	       "[UrlFile] [nvarchar](256) NULL,",
	       "[Packing] [nvarchar](256) NULL,",
	       "[NamberCatalog] [nvarchar](256) NULL,",
	       "[SaleId] [int] NOT NULL,",
	       "[MoneyId] [nvarchar](50) NOT NULL,",
           "CONSTRAINT [PK_mytrip_storeproduct] PRIMARY KEY CLUSTERED", 
           "(",
	       "[ProductId] ASC",
           ")WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]",
           ") ON [PRIMARY]",
           "END",
           "IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[mytrip_storevotes]') AND type in (N'U'))",
           "BEGIN",
           "CREATE TABLE [dbo].[mytrip_storevotes](",
	       "[VotesId] [int] NOT NULL,",
	       "[ProductId] [int] NOT NULL,",
	       "[Vote] [int] NOT NULL,",
	       "[UserName] [nvarchar](100) NOT NULL,",
	       "[Reviews] [nvarchar](max) NULL,",
	       "[CreationDate] [datetime] NOT NULL,",
           "CONSTRAINT [PK_mytrip_storevotes] PRIMARY KEY CLUSTERED", 
           "(",
	       "[VotesId] ASC",
           ")WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]",
           ") ON [PRIMARY]",
           "END",
           "IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[mytrip_storeorderisproduct]') AND type in (N'U'))",
           "BEGIN",
           "CREATE TABLE [dbo].[mytrip_storeorderisproduct](",
	       "[ProductId] [int] NOT NULL,",
	       "[Count] [int] NOT NULL,",
	       "[OrderId] [int] NOT NULL,",
	       "[Price] [decimal](18, 2) NOT NULL,",
	       "[MoneyId] [nvarchar](50) NOT NULL,",
           "CONSTRAINT [PK_mytrip_storeorderisproduct] PRIMARY KEY CLUSTERED", 
           "(",
	       "[ProductId] ASC,",
	       "[OrderId] ASC",
           ")WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]",
           ") ON [PRIMARY]",
           "END",
           "IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_mytrip_storedepartment_mytrip_storedepartment]') AND parent_object_id = OBJECT_ID(N'[dbo].[mytrip_storedepartment]'))",
           "ALTER TABLE [dbo].[mytrip_storedepartment]  WITH CHECK ADD  CONSTRAINT [FK_mytrip_storedepartment_mytrip_storedepartment] FOREIGN KEY([SubDepartmentId])",
           "REFERENCES [dbo].[mytrip_storedepartment] ([DepartmentId])",
           "IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_mytrip_storedepartment_mytrip_storedepartment]') AND parent_object_id = OBJECT_ID(N'[dbo].[mytrip_storedepartment]'))",
           "ALTER TABLE [dbo].[mytrip_storedepartment] CHECK CONSTRAINT [FK_mytrip_storedepartment_mytrip_storedepartment]",

           "IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_mytrip_storedepartment_mytrip_storesale]') AND parent_object_id = OBJECT_ID(N'[dbo].[mytrip_storedepartment]'))",
           "ALTER TABLE [dbo].[mytrip_storedepartment]  WITH CHECK ADD  CONSTRAINT [FK_mytrip_storedepartment_mytrip_storesale] FOREIGN KEY([SaleId])",
           "REFERENCES [dbo].[mytrip_storesale] ([SaleId])",
           "IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_mytrip_storedepartment_mytrip_storesale]') AND parent_object_id = OBJECT_ID(N'[dbo].[mytrip_storedepartment]'))",
           "ALTER TABLE [dbo].[mytrip_storedepartment] CHECK CONSTRAINT [FK_mytrip_storedepartment_mytrip_storesale]",

           "IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_mytrip_storeorder_mytrip_storeprofile]') AND parent_object_id = OBJECT_ID(N'[dbo].[mytrip_storeorder]'))",
           "ALTER TABLE [dbo].[mytrip_storeorder]  WITH CHECK ADD  CONSTRAINT [FK_mytrip_storeorder_mytrip_storeprofile] FOREIGN KEY([ProfileId])",
           "REFERENCES [dbo].[mytrip_storeprofile] ([ProfileId])",
           "IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_mytrip_storeorder_mytrip_storeprofile]') AND parent_object_id = OBJECT_ID(N'[dbo].[mytrip_storeorder]'))",
           "ALTER TABLE [dbo].[mytrip_storeorder] CHECK CONSTRAINT [FK_mytrip_storeorder_mytrip_storeprofile]",

           "IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_mytrip_storeorder_mytrip_storemanageorder]') AND parent_object_id = OBJECT_ID(N'[dbo].[mytrip_storeorderisproduct]'))",
           "ALTER TABLE [dbo].[mytrip_storeorderisproduct]  WITH CHECK ADD  CONSTRAINT [FK_mytrip_storeorder_mytrip_storemanageorder] FOREIGN KEY([OrderId])",
           "REFERENCES [dbo].[mytrip_storeorder] ([OrderId])",
           "IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_mytrip_storeorder_mytrip_storemanageorder]') AND parent_object_id = OBJECT_ID(N'[dbo].[mytrip_storeorderisproduct]'))",
           "ALTER TABLE [dbo].[mytrip_storeorderisproduct] CHECK CONSTRAINT [FK_mytrip_storeorder_mytrip_storemanageorder]",

           "IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_mytrip_storeorder_mytrip_storeproduct]') AND parent_object_id = OBJECT_ID(N'[dbo].[mytrip_storeorderisproduct]'))",
           "ALTER TABLE [dbo].[mytrip_storeorderisproduct]  WITH CHECK ADD  CONSTRAINT [FK_mytrip_storeorder_mytrip_storeproduct] FOREIGN KEY([ProductId])",
           "REFERENCES [dbo].[mytrip_storeproduct] ([ProductId])",
           "IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_mytrip_storeorder_mytrip_storeproduct]') AND parent_object_id = OBJECT_ID(N'[dbo].[mytrip_storeorderisproduct]'))",
           "ALTER TABLE [dbo].[mytrip_storeorderisproduct] CHECK CONSTRAINT [FK_mytrip_storeorder_mytrip_storeproduct]",

           "IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_mytrip_storeproducer_mytrip_storesale]') AND parent_object_id = OBJECT_ID(N'[dbo].[mytrip_storeproducer]'))",
           "ALTER TABLE [dbo].[mytrip_storeproducer]  WITH CHECK ADD  CONSTRAINT [FK_mytrip_storeproducer_mytrip_storesale] FOREIGN KEY([SaleId])",
           "REFERENCES [dbo].[mytrip_storesale] ([SaleId])",
           "IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_mytrip_storeproducer_mytrip_storesale]') AND parent_object_id = OBJECT_ID(N'[dbo].[mytrip_storeproducer]'))",
           "ALTER TABLE [dbo].[mytrip_storeproducer] CHECK CONSTRAINT [FK_mytrip_storeproducer_mytrip_storesale]",

           "IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_mytrip_storeproduct_mytrip_storedepartment]') AND parent_object_id = OBJECT_ID(N'[dbo].[mytrip_storeproduct]'))",
           "ALTER TABLE [dbo].[mytrip_storeproduct]  WITH CHECK ADD  CONSTRAINT [FK_mytrip_storeproduct_mytrip_storedepartment] FOREIGN KEY([DepartmentId])",
           "REFERENCES [dbo].[mytrip_storedepartment] ([DepartmentId])",
           "IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_mytrip_storeproduct_mytrip_storedepartment]') AND parent_object_id = OBJECT_ID(N'[dbo].[mytrip_storeproduct]'))",
           "ALTER TABLE [dbo].[mytrip_storeproduct] CHECK CONSTRAINT [FK_mytrip_storeproduct_mytrip_storedepartment]",

           "IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_mytrip_storeproduct_mytrip_storeproducer]') AND parent_object_id = OBJECT_ID(N'[dbo].[mytrip_storeproduct]'))",
           "ALTER TABLE [dbo].[mytrip_storeproduct]  WITH CHECK ADD  CONSTRAINT [FK_mytrip_storeproduct_mytrip_storeproducer] FOREIGN KEY([ProducerId])",
           "REFERENCES [dbo].[mytrip_storeproducer] ([ProducerId])",
           "IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_mytrip_storeproduct_mytrip_storeproducer]') AND parent_object_id = OBJECT_ID(N'[dbo].[mytrip_storeproduct]'))",
           "ALTER TABLE [dbo].[mytrip_storeproduct] CHECK CONSTRAINT [FK_mytrip_storeproduct_mytrip_storeproducer]",

           "IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_mytrip_storeproduct_mytrip_storesale]') AND parent_object_id = OBJECT_ID(N'[dbo].[mytrip_storeproduct]'))",
           "ALTER TABLE [dbo].[mytrip_storeproduct]  WITH CHECK ADD  CONSTRAINT [FK_mytrip_storeproduct_mytrip_storesale] FOREIGN KEY([SaleId])",
           "REFERENCES [dbo].[mytrip_storesale] ([SaleId])",
           "IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_mytrip_storeproduct_mytrip_storesale]') AND parent_object_id = OBJECT_ID(N'[dbo].[mytrip_storeproduct]'))",
           "ALTER TABLE [dbo].[mytrip_storeproduct] CHECK CONSTRAINT [FK_mytrip_storeproduct_mytrip_storesale]",

           "IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_mytrip_storevotes_mytrip_storeproduct]') AND parent_object_id = OBJECT_ID(N'[dbo].[mytrip_storevotes]'))",
           "ALTER TABLE [dbo].[mytrip_storevotes]  WITH CHECK ADD  CONSTRAINT [FK_mytrip_storevotes_mytrip_storeproduct] FOREIGN KEY([ProductId])",
           "REFERENCES [dbo].[mytrip_storeproduct] ([ProductId])",
           "IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_mytrip_storevotes_mytrip_storeproduct]') AND parent_object_id = OBJECT_ID(N'[dbo].[mytrip_storevotes]'))",
           "ALTER TABLE [dbo].[mytrip_storevotes] CHECK CONSTRAINT [FK_mytrip_storevotes_mytrip_storeproduct]"
           };
            return result;

        }
        private string[] deleteScriptMSSQL()
        {
            string[] result = {
            "IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_mytrip_storedepartment_mytrip_storedepartment]') AND parent_object_id = OBJECT_ID(N'[dbo].[mytrip_storedepartment]'))",
            "ALTER TABLE [dbo].[mytrip_storedepartment] DROP CONSTRAINT [FK_mytrip_storedepartment_mytrip_storedepartment]",

            "IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_mytrip_storedepartment_mytrip_storesale]') AND parent_object_id = OBJECT_ID(N'[dbo].[mytrip_storedepartment]'))",
            "ALTER TABLE [dbo].[mytrip_storedepartment] DROP CONSTRAINT [FK_mytrip_storedepartment_mytrip_storesale]",

            "IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_mytrip_storeorder_mytrip_storeprofile]') AND parent_object_id = OBJECT_ID(N'[dbo].[mytrip_storeorder]'))",
            "ALTER TABLE [dbo].[mytrip_storeorder] DROP CONSTRAINT [FK_mytrip_storeorder_mytrip_storeprofile]",

            "IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_mytrip_storeorder_mytrip_storemanageorder]') AND parent_object_id = OBJECT_ID(N'[dbo].[mytrip_storeorderisproduct]'))",
            "ALTER TABLE [dbo].[mytrip_storeorderisproduct] DROP CONSTRAINT [FK_mytrip_storeorder_mytrip_storemanageorder]",

            "IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_mytrip_storeorder_mytrip_storeproduct]') AND parent_object_id = OBJECT_ID(N'[dbo].[mytrip_storeorderisproduct]'))",
            "ALTER TABLE [dbo].[mytrip_storeorderisproduct] DROP CONSTRAINT [FK_mytrip_storeorder_mytrip_storeproduct]",

            "IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_mytrip_storeproducer_mytrip_storesale]') AND parent_object_id = OBJECT_ID(N'[dbo].[mytrip_storeproducer]'))",
            "ALTER TABLE [dbo].[mytrip_storeproducer] DROP CONSTRAINT [FK_mytrip_storeproducer_mytrip_storesale]",

            "IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_mytrip_storeproduct_mytrip_storedepartment]') AND parent_object_id = OBJECT_ID(N'[dbo].[mytrip_storeproduct]'))",
            "ALTER TABLE [dbo].[mytrip_storeproduct] DROP CONSTRAINT [FK_mytrip_storeproduct_mytrip_storedepartment]",

            "IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_mytrip_storeproduct_mytrip_storeproducer]') AND parent_object_id = OBJECT_ID(N'[dbo].[mytrip_storeproduct]'))",
            "ALTER TABLE [dbo].[mytrip_storeproduct] DROP CONSTRAINT [FK_mytrip_storeproduct_mytrip_storeproducer]",

            "IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_mytrip_storeproduct_mytrip_storesale]') AND parent_object_id = OBJECT_ID(N'[dbo].[mytrip_storeproduct]'))",
            "ALTER TABLE [dbo].[mytrip_storeproduct] DROP CONSTRAINT [FK_mytrip_storeproduct_mytrip_storesale]",

            "IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_mytrip_storevotes_mytrip_storeproduct]') AND parent_object_id = OBJECT_ID(N'[dbo].[mytrip_storevotes]'))",
            "ALTER TABLE [dbo].[mytrip_storevotes] DROP CONSTRAINT [FK_mytrip_storevotes_mytrip_storeproduct]",

            "IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[mytrip_storeorderisproduct]') AND type in (N'U'))",
            "DROP TABLE [dbo].[mytrip_storeorderisproduct]",

            "IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[mytrip_storevotes]') AND type in (N'U'))",
            "DROP TABLE [dbo].[mytrip_storevotes]",

            "IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[mytrip_storeproduct]') AND type in (N'U'))",
            "DROP TABLE [dbo].[mytrip_storeproduct]",
            "IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[mytrip_storeproducer]') AND type in (N'U'))",
            "DROP TABLE [dbo].[mytrip_storeproducer]",
 
            "IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[mytrip_storedepartment]') AND type in (N'U'))",
            "DROP TABLE [dbo].[mytrip_storedepartment]",

            "IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[mytrip_storeorder]') AND type in (N'U'))",
            "DROP TABLE [dbo].[mytrip_storeorder]",

            "IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[mytrip_storeprofile]') AND type in (N'U'))",
            "DROP TABLE [dbo].[mytrip_storeprofile]",

            "IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[mytrip_storesale]') AND type in (N'U'))",
            "DROP TABLE [dbo].[mytrip_storesale]",

            "IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[mytrip_storeseller]') AND type in (N'U'))",
            "DROP TABLE [dbo].[mytrip_storeseller]"
                              };
            return result;
        }
        private string[] scriptMYSQL()
        {
            string[] result = {
            "CREATE TABLE IF NOT EXISTS mytrip_storeprofile(",
            "ProfileId INT (11) NOT NULL,",
            "UserName VARCHAR (256) NOT NULL,",
            "UserEmail VARCHAR (256) NOT NULL,",
            "Address TEXT DEFAULT NULL,",
            "Phone VARCHAR (256) DEFAULT NULL,",
            "IsAnonym BIT (1) NOT NULL,",
            "FirstName VARCHAR (256) NOT NULL,",
            "LastName VARCHAR (256) DEFAULT NULL,",
            "Organization VARCHAR (256) DEFAULT NULL,",
            "OrganizationINN VARCHAR (256) DEFAULT NULL,",
            "OrganizationKPP VARCHAR (256) DEFAULT NULL,",
            "UserIP VARCHAR (256) NOT NULL,",
            "PRIMARY KEY (ProfileId)",
            ")",
            "ENGINE = INNODB",
            "AVG_ROW_LENGTH = 8192",
            "CHARACTER SET cp1251",
            "COLLATE cp1251_general_ci;",

            "CREATE TABLE IF NOT EXISTS mytrip_storesale(",
            "SaleId INT (11) NOT NULL,",
            "Sale INT (11) NOT NULL,",
            "Title VARCHAR (256) DEFAULT NULL,",
            "CreationDate DATETIME NOT NULL,",
            "CloseDate DATETIME NOT NULL,",
            "UserName VARCHAR (256) DEFAULT NULL,",
            "StartDate DATETIME NOT NULL,",
            "ManagerName VARCHAR (256) NOT NULL,",
            "PRIMARY KEY (SaleId)",
            ")",
            "ENGINE = INNODB",
            "AVG_ROW_LENGTH = 5461",
            "CHARACTER SET cp1251",
            "COLLATE cp1251_general_ci;",

            "CREATE TABLE IF NOT EXISTS mytrip_storeseller(",
            "SellerId INT (11) NOT NULL,",
            "Organization VARCHAR (256) DEFAULT NULL,",
            "Address TEXT DEFAULT NULL,",
            "Phone VARCHAR (256) DEFAULT NULL,",
            "Email VARCHAR (256) DEFAULT NULL,",
            "OrganizationINN VARCHAR (256) DEFAULT NULL,",
            "OrganizationKPP VARCHAR (256) DEFAULT NULL,",
            "BankAccountSeller VARCHAR (256) DEFAULT NULL,",
            "BankAccountBIK VARCHAR (256) DEFAULT NULL,",
            "Bank VARCHAR (256) DEFAULT NULL,",
            "BankAccount VARCHAR (256) DEFAULT NULL,",
            "Director VARCHAR (256) DEFAULT NULL,",
            "Accountant VARCHAR (256) DEFAULT NULL,",
            "LiteNDS BIT (1) NOT NULL,",
            "Culture VARCHAR (50) NOT NULL,",
            "AllCulture BIT (1) NOT NULL,",
            "PRIMARY KEY (SellerId)",
            ")",
            "ENGINE = INNODB",
            "AVG_ROW_LENGTH = 16384",
            "CHARACTER SET cp1251",
            "COLLATE cp1251_general_ci;",

            "CREATE TABLE IF NOT EXISTS mytrip_storedepartment(",
            "DepartmentId INT (11) NOT NULL,",
            "Title VARCHAR (256) NOT NULL,",
            "Path VARCHAR (256) NOT NULL,",
            "Culture VARCHAR (50) NOT NULL,",
            "AllCulture BIT (1) NOT NULL,",
            "UserName VARCHAR (100) NOT NULL,",
            "CreationDate DATETIME NOT NULL,",
            "Body TEXT DEFAULT NULL,",
            "SubDepartmentId INT (11) NOT NULL,",
            "SaleId INT (11) NOT NULL,",
            "PRIMARY KEY (DepartmentId),",
            "INDEX IX_mytrip_storedepartment (SubDepartmentId),",
            "INDEX mytrip_storedepartment_FK1 (SaleId),",
            "CONSTRAINT mytrip_storedepartment_FK1 FOREIGN KEY (SaleId)",
            "REFERENCES mytrip_storesale (SaleId),",
            "CONSTRAINT mytrip_storedepartment_FK2 FOREIGN KEY (SubDepartmentId)",
            "REFERENCES mytrip_storedepartment (DepartmentId)",
            ")",
            "ENGINE = INNODB",
            "AVG_ROW_LENGTH = 8192",
            "CHARACTER SET cp1251",
            "COLLATE cp1251_general_ci;",

            "CREATE TABLE IF NOT EXISTS mytrip_storeorder(",
            "OrderId INT (11) NOT NULL,",
            "Status INT (11) NOT NULL,",
            "Culture VARCHAR (256) NOT NULL,",
            "CreationDate DATETIME NOT NULL,",
            "ManagerName VARCHAR (256) DEFAULT NULL,",
            "Delivery DECIMAL (18, 2) NOT NULL,",
            "MoneyId VARCHAR (50) NOT NULL,",
            "PriceInWords VARCHAR (256) DEFAULT NULL,",
            "NamberAccount INT (11) DEFAULT NULL,",
            "DateAccount DATETIME DEFAULT NULL,",
            "ProfileId INT (11) NOT NULL,",
            "AccountPage TEXT DEFAULT NULL,",
            "PRIMARY KEY (OrderId),",
            "INDEX mytrip_storeorder_FK1 (MoneyId),",
            "INDEX mytrip_storeorder_FK5 (ProfileId),",
            "CONSTRAINT mytrip_storeorder_FK5 FOREIGN KEY (ProfileId)",
            "REFERENCES mytrip_storeprofile (ProfileId)",
            ")",
            "ENGINE = INNODB",
            "AVG_ROW_LENGTH = 9830",
            "CHARACTER SET cp1251",
            "COLLATE cp1251_general_ci;",

            "CREATE TABLE IF NOT EXISTS mytrip_storeproducer(",
            "ProducerId INT (11) NOT NULL,",
            "Title VARCHAR (256) NOT NULL,",
            "Body TEXT DEFAULT NULL,",
            "Path VARCHAR (256) NOT NULL,",
            "Culture VARCHAR (50) NOT NULL,",
            "AllCulture BIT (1) NOT NULL,",
            "UserName VARCHAR (100) NOT NULL,",
            "CreationDate DATETIME NOT NULL,",
            "SaleId INT (11) NOT NULL,",
            "PRIMARY KEY (ProducerId),",
            "INDEX mytrip_storeproducer_FK1 (SaleId),",
            "CONSTRAINT mytrip_storeproducer_FK1 FOREIGN KEY (SaleId)",
            "REFERENCES mytrip_storesale (SaleId)",
            ")",
            "ENGINE = INNODB",
            "AVG_ROW_LENGTH = 16384",
            "CHARACTER SET cp1251",
            "COLLATE cp1251_general_ci;",

            "CREATE TABLE IF NOT EXISTS mytrip_storeproduct(",
            "ProductId INT (11) NOT NULL,",
            "DepartmentId INT (11) NOT NULL,",
            "ProducerId INT (11) NOT NULL,",
            "Title VARCHAR (256) NOT NULL,",
            "Path VARCHAR (256) NOT NULL,",
            "Details TEXT DEFAULT NULL,",
            "Body TEXT DEFAULT NULL,",
            "CreationDate DATETIME NOT NULL,",
            "UserName VARCHAR (100) NOT NULL,",
            "Culture VARCHAR (50) NOT NULL,",
            "AllCulture BIT (1) NOT NULL,",
            "Price DECIMAL (18, 2) NOT NULL,",
            "TotalVotes DECIMAL (4, 2) NOT NULL,",
            "TotalCount INT (11) NOT NULL,",
            "ViewPrice BIT (1) NOT NULL,",
            "ViewVotes BIT (1) NOT NULL,",
            "ViewCount BIT (1) NOT NULL,",
            "UrlFile VARCHAR (256) DEFAULT NULL,",
            "Packing VARCHAR (256) DEFAULT NULL,",
            "NamberCatalog VARCHAR (256) DEFAULT NULL,",
            "SaleId INT (11) NOT NULL,",
            "MoneyId VARCHAR (50) NOT NULL,",
            "PRIMARY KEY (ProductId),",
            "INDEX IX_mytrip_storeproduct_department (DepartmentId),",
            "INDEX IX_mytrip_storeproduct_producer (ProducerId),",
            "INDEX mytrip_storeproduct_FK1 (SaleId),",
            "INDEX mytrip_storeproduct_FK2 (MoneyId),",
            "CONSTRAINT FK_mytrip_storeproduct_mytrip_storedepartment FOREIGN KEY (DepartmentId)",
            "REFERENCES mytrip_storedepartment (DepartmentId),",
            "CONSTRAINT FK_mytrip_storeproduct_mytrip_storeproducer FOREIGN KEY (ProducerId)",
            "REFERENCES mytrip_storeproducer (ProducerId),",
            "CONSTRAINT mytrip_storeproduct_FK1 FOREIGN KEY (SaleId)",
            "REFERENCES mytrip_storesale (SaleId)",
            ")",
            "ENGINE = INNODB",
            "AVG_ROW_LENGTH = 1328",
            "CHARACTER SET cp1251",
            "COLLATE cp1251_general_ci;",

            "CREATE TABLE IF NOT EXISTS mytrip_storeorderisproduct(",
            "ProductId INT (11) NOT NULL,",
            "Count INT (11) NOT NULL,",
            "OrderId INT (11) NOT NULL,",
            "Price DECIMAL (18, 2) NOT NULL,",
            "MoneyId VARCHAR (50) NOT NULL,",
            "PRIMARY KEY (ProductId, OrderId),",
            "INDEX mytrip_storeorderisproduct_FK1 (OrderId),",
            "INDEX mytrip_storeorderisproduct_FK2 (MoneyId),",
            "CONSTRAINT mytrip_storeorder_FK2 FOREIGN KEY (ProductId)",
            "REFERENCES mytrip_storeproduct (ProductId),",
            "CONSTRAINT mytrip_storeorderisproduct_FK1 FOREIGN KEY (OrderId)",
            "REFERENCES mytrip_storeorder (OrderId)",
            ")",
            "ENGINE = INNODB",
            "AVG_ROW_LENGTH = 1489",
            "CHARACTER SET cp1251",
            "COLLATE cp1251_general_ci;",

            "CREATE TABLE IF NOT EXISTS mytrip_storevotes(",
            "VotesId INT (11) NOT NULL,",
            "ProductId INT (11) NOT NULL,",
            "Vote INT (11) NOT NULL,",
            "UserName VARCHAR (100) NOT NULL,",
            "Reviews TEXT DEFAULT NULL,",
            "CreationDate DATETIME NOT NULL,",
            "PRIMARY KEY (VotesId),",
            "INDEX IX_mytrip_storevotes (ProductId),",
            "CONSTRAINT FK_mytrip_storevotes_mytrip_storeproduct FOREIGN KEY (ProductId)",
            "REFERENCES mytrip_storeproduct (ProductId)",
            ")",
            "ENGINE = INNODB",
            "AVG_ROW_LENGTH = 4096",
            "CHARACTER SET cp1251",
            "COLLATE cp1251_general_ci;"                
                             };
            return result;

        }
        private string[] deleteScriptMYSQL()
        {
            string[] result = {
            "DROP TABLE IF EXISTS mytrip_storevotes;",                 
            "DROP TABLE IF EXISTS mytrip_storeorderisproduct;",
            "DROP TABLE IF EXISTS mytrip_storeproduct;",
            "DROP TABLE IF EXISTS mytrip_storeproducer;",
            "DROP TABLE IF EXISTS mytrip_storeorder;",
            "DROP TABLE IF EXISTS mytrip_storedepartment;",
            "DROP TABLE IF EXISTS mytrip_storeseller;",
            "DROP TABLE IF EXISTS mytrip_storesale;",
            "DROP TABLE IF EXISTS mytrip_storeprofile;"
                              };
            return result;
        }
    }
}
