//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace mtm.Tourism.Repository.DataEntities
{
    public partial class mytrip_toursvariants
    {
        #region Primitive Properties
    
        public virtual string Hotel
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> Latitude
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> Longitude
        {
            get;
            set;
        }
    
        public virtual string MoneyId
        {
            get;
            set;
        }
    
        public virtual decimal Price
        {
            get;
            set;
        }
    
        public virtual string Services
        {
            get;
            set;
        }
    
        public virtual int TourId
        {
            get { return _tourId; }
            set
            {
                if (_tourId != value)
                {
                    if (mytrip_tours != null && mytrip_tours.TourId != value)
                    {
                        mytrip_tours = null;
                    }
                    _tourId = value;
                }
            }
        }
        private int _tourId;
    
        public virtual string UserName
        {
            get;
            set;
        }
    
        public virtual int VariantId
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual mytrip_tours mytrip_tours
        {
            get { return _mytrip_tours; }
            set
            {
                if (!ReferenceEquals(_mytrip_tours, value))
                {
                    var previousValue = _mytrip_tours;
                    _mytrip_tours = value;
                    Fixupmytrip_tours(previousValue);
                }
            }
        }
        private mytrip_tours _mytrip_tours;

        #endregion
        #region Association Fixup
    
        private void Fixupmytrip_tours(mytrip_tours previousValue)
        {
            if (previousValue != null && previousValue.mytrip_toursvariants.Contains(this))
            {
                previousValue.mytrip_toursvariants.Remove(this);
            }
    
            if (mytrip_tours != null)
            {
                if (!mytrip_tours.mytrip_toursvariants.Contains(this))
                {
                    mytrip_tours.mytrip_toursvariants.Add(this);
                }
                if (TourId != mytrip_tours.TourId)
                {
                    TourId = mytrip_tours.TourId;
                }
            }
        }

        #endregion
    }
}
