//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace mtm.Tourism.Repository.DataEntities
{
    public partial class mytrip_tourscategory
    {
        #region Primitive Properties
    
        public virtual bool AllCulture
        {
            get;
            set;
        }
    
        public virtual string Body
        {
            get;
            set;
        }
    
        public virtual int CategoryId
        {
            get;
            set;
        }
    
        public virtual System.DateTime CreateDate
        {
            get;
            set;
        }
    
        public virtual string Culture
        {
            get;
            set;
        }
    
        public virtual string Path
        {
            get;
            set;
        }
    
        public virtual string SeoDescription
        {
            get;
            set;
        }
    
        public virtual string SeoKeyword
        {
            get;
            set;
        }
    
        public virtual string SeoTitle
        {
            get;
            set;
        }
    
        public virtual int SubCategoryId
        {
            get { return _subCategoryId; }
            set
            {
                if (_subCategoryId != value)
                {
                    if (mytrip_tourscategory2 != null && mytrip_tourscategory2.CategoryId != value)
                    {
                        mytrip_tourscategory2 = null;
                    }
                    _subCategoryId = value;
                }
            }
        }
        private int _subCategoryId;
    
        public virtual string Title
        {
            get;
            set;
        }
    
        public virtual string UserName
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<mytrip_tours> mytrip_tours
        {
            get
            {
                if (_mytrip_tours == null)
                {
                    var newCollection = new FixupCollection<mytrip_tours>();
                    newCollection.CollectionChanged += Fixupmytrip_tours;
                    _mytrip_tours = newCollection;
                }
                return _mytrip_tours;
            }
            set
            {
                if (!ReferenceEquals(_mytrip_tours, value))
                {
                    var previousValue = _mytrip_tours as FixupCollection<mytrip_tours>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupmytrip_tours;
                    }
                    _mytrip_tours = value;
                    var newValue = value as FixupCollection<mytrip_tours>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupmytrip_tours;
                    }
                }
            }
        }
        private ICollection<mytrip_tours> _mytrip_tours;
    
        public virtual ICollection<mytrip_tourscategory> mytrip_tourscategory1
        {
            get
            {
                if (_mytrip_tourscategory1 == null)
                {
                    var newCollection = new FixupCollection<mytrip_tourscategory>();
                    newCollection.CollectionChanged += Fixupmytrip_tourscategory1;
                    _mytrip_tourscategory1 = newCollection;
                }
                return _mytrip_tourscategory1;
            }
            set
            {
                if (!ReferenceEquals(_mytrip_tourscategory1, value))
                {
                    var previousValue = _mytrip_tourscategory1 as FixupCollection<mytrip_tourscategory>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupmytrip_tourscategory1;
                    }
                    _mytrip_tourscategory1 = value;
                    var newValue = value as FixupCollection<mytrip_tourscategory>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupmytrip_tourscategory1;
                    }
                }
            }
        }
        private ICollection<mytrip_tourscategory> _mytrip_tourscategory1;
    
        public virtual mytrip_tourscategory mytrip_tourscategory2
        {
            get { return _mytrip_tourscategory2; }
            set
            {
                if (!ReferenceEquals(_mytrip_tourscategory2, value))
                {
                    var previousValue = _mytrip_tourscategory2;
                    _mytrip_tourscategory2 = value;
                    Fixupmytrip_tourscategory2(previousValue);
                }
            }
        }
        private mytrip_tourscategory _mytrip_tourscategory2;

        #endregion
        #region Association Fixup
    
        private void Fixupmytrip_tourscategory2(mytrip_tourscategory previousValue)
        {
            if (previousValue != null && previousValue.mytrip_tourscategory1.Contains(this))
            {
                previousValue.mytrip_tourscategory1.Remove(this);
            }
    
            if (mytrip_tourscategory2 != null)
            {
                if (!mytrip_tourscategory2.mytrip_tourscategory1.Contains(this))
                {
                    mytrip_tourscategory2.mytrip_tourscategory1.Add(this);
                }
                if (SubCategoryId != mytrip_tourscategory2.CategoryId)
                {
                    SubCategoryId = mytrip_tourscategory2.CategoryId;
                }
            }
        }
    
        private void Fixupmytrip_tours(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (mytrip_tours item in e.NewItems)
                {
                    item.mytrip_tourscategory = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (mytrip_tours item in e.OldItems)
                {
                    if (ReferenceEquals(item.mytrip_tourscategory, this))
                    {
                        item.mytrip_tourscategory = null;
                    }
                }
            }
        }
    
        private void Fixupmytrip_tourscategory1(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (mytrip_tourscategory item in e.NewItems)
                {
                    item.mytrip_tourscategory2 = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (mytrip_tourscategory item in e.OldItems)
                {
                    if (ReferenceEquals(item.mytrip_tourscategory2, this))
                    {
                        item.mytrip_tourscategory2 = null;
                    }
                }
            }
        }

        #endregion
    }
}
