//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace mtm.Tourism.Repository.DataEntities
{
    public partial class mytrip_tourscountry
    {
        #region Primitive Properties
    
        public virtual bool AllCulture
        {
            get;
            set;
        }
    
        public virtual string Body
        {
            get;
            set;
        }
    
        public virtual int CountryId
        {
            get;
            set;
        }
    
        public virtual System.DateTime CreateDate
        {
            get;
            set;
        }
    
        public virtual string Culture
        {
            get;
            set;
        }
    
        public virtual string Path
        {
            get;
            set;
        }
    
        public virtual string SeoDescription
        {
            get;
            set;
        }
    
        public virtual string SeoKeyword
        {
            get;
            set;
        }
    
        public virtual string SeoTitle
        {
            get;
            set;
        }
    
        public virtual string Title
        {
            get;
            set;
        }
    
        public virtual string UserName
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<mytrip_tours> mytrip_tours
        {
            get
            {
                if (_mytrip_tours == null)
                {
                    var newCollection = new FixupCollection<mytrip_tours>();
                    newCollection.CollectionChanged += Fixupmytrip_tours;
                    _mytrip_tours = newCollection;
                }
                return _mytrip_tours;
            }
            set
            {
                if (!ReferenceEquals(_mytrip_tours, value))
                {
                    var previousValue = _mytrip_tours as FixupCollection<mytrip_tours>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupmytrip_tours;
                    }
                    _mytrip_tours = value;
                    var newValue = value as FixupCollection<mytrip_tours>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupmytrip_tours;
                    }
                }
            }
        }
        private ICollection<mytrip_tours> _mytrip_tours;

        #endregion
        #region Association Fixup
    
        private void Fixupmytrip_tours(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (mytrip_tours item in e.NewItems)
                {
                    item.mytrip_tourscountry = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (mytrip_tours item in e.OldItems)
                {
                    if (ReferenceEquals(item.mytrip_tourscountry, this))
                    {
                        item.mytrip_tourscountry = null;
                    }
                }
            }
        }

        #endregion
    }
}
