//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace mtm.Tourism.Repository.DataEntities
{
    public partial class mytrip_tours
    {
        #region Primitive Properties
    
        public virtual bool AllCulture
        {
            get;
            set;
        }
    
        public virtual string Body
        {
            get;
            set;
        }
    
        public virtual int CategoryId
        {
            get { return _categoryId; }
            set
            {
                if (_categoryId != value)
                {
                    if (mytrip_tourscategory != null && mytrip_tourscategory.CategoryId != value)
                    {
                        mytrip_tourscategory = null;
                    }
                    _categoryId = value;
                }
            }
        }
        private int _categoryId;
    
        public virtual System.DateTime CloseTourDate
        {
            get;
            set;
        }
    
        public virtual int CountryId
        {
            get { return _countryId; }
            set
            {
                if (_countryId != value)
                {
                    if (mytrip_tourscountry != null && mytrip_tourscountry.CountryId != value)
                    {
                        mytrip_tourscountry = null;
                    }
                    _countryId = value;
                }
            }
        }
        private int _countryId;
    
        public virtual System.DateTime CreateDate
        {
            get;
            set;
        }
    
        public virtual string Culture
        {
            get;
            set;
        }
    
        public virtual string Imige
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> Latitude
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> Longitude
        {
            get;
            set;
        }
    
        public virtual decimal MinPrice
        {
            get;
            set;
        }
    
        public virtual string MoneyId
        {
            get;
            set;
        }
    
        public virtual string Path
        {
            get;
            set;
        }
    
        public virtual string SeoDescription
        {
            get;
            set;
        }
    
        public virtual string SeoKeyword
        {
            get;
            set;
        }
    
        public virtual string SeoTitle
        {
            get;
            set;
        }
    
        public virtual System.DateTime StartDate
        {
            get;
            set;
        }
    
        public virtual System.DateTime StopDate
        {
            get;
            set;
        }
    
        public virtual string Title
        {
            get;
            set;
        }
    
        public virtual int TourId
        {
            get;
            set;
        }
    
        public virtual string UserName
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<mytrip_toursvariants> mytrip_toursvariants
        {
            get
            {
                if (_mytrip_toursvariants == null)
                {
                    var newCollection = new FixupCollection<mytrip_toursvariants>();
                    newCollection.CollectionChanged += Fixupmytrip_toursvariants;
                    _mytrip_toursvariants = newCollection;
                }
                return _mytrip_toursvariants;
            }
            set
            {
                if (!ReferenceEquals(_mytrip_toursvariants, value))
                {
                    var previousValue = _mytrip_toursvariants as FixupCollection<mytrip_toursvariants>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupmytrip_toursvariants;
                    }
                    _mytrip_toursvariants = value;
                    var newValue = value as FixupCollection<mytrip_toursvariants>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupmytrip_toursvariants;
                    }
                }
            }
        }
        private ICollection<mytrip_toursvariants> _mytrip_toursvariants;
    
        public virtual mytrip_tourscategory mytrip_tourscategory
        {
            get { return _mytrip_tourscategory; }
            set
            {
                if (!ReferenceEquals(_mytrip_tourscategory, value))
                {
                    var previousValue = _mytrip_tourscategory;
                    _mytrip_tourscategory = value;
                    Fixupmytrip_tourscategory(previousValue);
                }
            }
        }
        private mytrip_tourscategory _mytrip_tourscategory;
    
        public virtual mytrip_tourscountry mytrip_tourscountry
        {
            get { return _mytrip_tourscountry; }
            set
            {
                if (!ReferenceEquals(_mytrip_tourscountry, value))
                {
                    var previousValue = _mytrip_tourscountry;
                    _mytrip_tourscountry = value;
                    Fixupmytrip_tourscountry(previousValue);
                }
            }
        }
        private mytrip_tourscountry _mytrip_tourscountry;

        #endregion
        #region Association Fixup
    
        private void Fixupmytrip_tourscategory(mytrip_tourscategory previousValue)
        {
            if (previousValue != null && previousValue.mytrip_tours.Contains(this))
            {
                previousValue.mytrip_tours.Remove(this);
            }
    
            if (mytrip_tourscategory != null)
            {
                if (!mytrip_tourscategory.mytrip_tours.Contains(this))
                {
                    mytrip_tourscategory.mytrip_tours.Add(this);
                }
                if (CategoryId != mytrip_tourscategory.CategoryId)
                {
                    CategoryId = mytrip_tourscategory.CategoryId;
                }
            }
        }
    
        private void Fixupmytrip_tourscountry(mytrip_tourscountry previousValue)
        {
            if (previousValue != null && previousValue.mytrip_tours.Contains(this))
            {
                previousValue.mytrip_tours.Remove(this);
            }
    
            if (mytrip_tourscountry != null)
            {
                if (!mytrip_tourscountry.mytrip_tours.Contains(this))
                {
                    mytrip_tourscountry.mytrip_tours.Add(this);
                }
                if (CountryId != mytrip_tourscountry.CountryId)
                {
                    CountryId = mytrip_tourscountry.CountryId;
                }
            }
        }
    
        private void Fixupmytrip_toursvariants(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (mytrip_toursvariants item in e.NewItems)
                {
                    item.mytrip_tours = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (mytrip_toursvariants item in e.OldItems)
                {
                    if (ReferenceEquals(item.mytrip_tours, this))
                    {
                        item.mytrip_tours = null;
                    }
                }
            }
        }

        #endregion
    }
}
