//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mytrip.Mvc.Model.Linq2sql.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=C:\\Users\\Mytrip.Mvc\\Documents\\MY-TRIP-M" +
            "VC-2\\VS2008\\1_A_JOB_Linq2sql\\Mytrip.Mvc.Web.Linq2sql\\App_Data\\mytripmvc.mdf;Inte" +
            "grated Security=True;User Instance=True")]
        public string mytripmvcConnectionString {
            get {
                return ((string)(this["mytripmvcConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=C:\\Users\\Margo\\Desktop\\2.0.241.1\\Mytrip" +
            ".Mvc.Web.Linq2sql\\App_Data\\mytripmvc.mdf;Integrated Security=True;User Instance=" +
            "True")]
        public string mytripmvcConnectionString1 {
            get {
                return ((string)(this["mytripmvcConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=C:\\Users\\Mytrip.Mvc\\Mytrip.Mvc_2.0\\VS20" +
            "08\\1_A_JOB_Linq2sql\\Mytrip.Mvc.Web.Linq2sql\\App_Data\\mytripmvc.mdf;Integrated Se" +
            "curity=True;User Instance=True")]
        public string mytripmvcConnectionString2 {
            get {
                return ((string)(this["mytripmvcConnectionString2"]));
            }
        }
    }
}
