//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Mytrip.Store.Repository.DataEntities
{
    public partial class mytrip_storeorderisproduct
    {
        #region Primitive Properties
    
        public virtual int ProductId
        {
            get { return _productId; }
            set
            {
                if (_productId != value)
                {
                    if (mytrip_storeproduct != null && mytrip_storeproduct.ProductId != value)
                    {
                        mytrip_storeproduct = null;
                    }
                    _productId = value;
                }
            }
        }
        private int _productId;
    
        public virtual int Count
        {
            get;
            set;
        }
    
        public virtual int OrderId
        {
            get { return _orderId; }
            set
            {
                if (_orderId != value)
                {
                    if (mytrip_storeorder != null && mytrip_storeorder.OrderId != value)
                    {
                        mytrip_storeorder = null;
                    }
                    _orderId = value;
                }
            }
        }
        private int _orderId;
    
        public virtual decimal Price
        {
            get;
            set;
        }
    
        public virtual string MoneyId
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual mytrip_storeorder mytrip_storeorder
        {
            get { return _mytrip_storeorder; }
            set
            {
                if (!ReferenceEquals(_mytrip_storeorder, value))
                {
                    var previousValue = _mytrip_storeorder;
                    _mytrip_storeorder = value;
                    Fixupmytrip_storeorder(previousValue);
                }
            }
        }
        private mytrip_storeorder _mytrip_storeorder;
    
        public virtual mytrip_storeproduct mytrip_storeproduct
        {
            get { return _mytrip_storeproduct; }
            set
            {
                if (!ReferenceEquals(_mytrip_storeproduct, value))
                {
                    var previousValue = _mytrip_storeproduct;
                    _mytrip_storeproduct = value;
                    Fixupmytrip_storeproduct(previousValue);
                }
            }
        }
        private mytrip_storeproduct _mytrip_storeproduct;

        #endregion
        #region Association Fixup
    
        private void Fixupmytrip_storeorder(mytrip_storeorder previousValue)
        {
            if (previousValue != null && previousValue.mytrip_storeorderisproduct.Contains(this))
            {
                previousValue.mytrip_storeorderisproduct.Remove(this);
            }
    
            if (mytrip_storeorder != null)
            {
                if (!mytrip_storeorder.mytrip_storeorderisproduct.Contains(this))
                {
                    mytrip_storeorder.mytrip_storeorderisproduct.Add(this);
                }
                if (OrderId != mytrip_storeorder.OrderId)
                {
                    OrderId = mytrip_storeorder.OrderId;
                }
            }
        }
    
        private void Fixupmytrip_storeproduct(mytrip_storeproduct previousValue)
        {
            if (previousValue != null && previousValue.mytrip_storeorderisproduct.Contains(this))
            {
                previousValue.mytrip_storeorderisproduct.Remove(this);
            }
    
            if (mytrip_storeproduct != null)
            {
                if (!mytrip_storeproduct.mytrip_storeorderisproduct.Contains(this))
                {
                    mytrip_storeproduct.mytrip_storeorderisproduct.Add(this);
                }
                if (ProductId != mytrip_storeproduct.ProductId)
                {
                    ProductId = mytrip_storeproduct.ProductId;
                }
            }
        }

        #endregion
    }
}
