//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Mytrip.Store.Repository.DataEntities
{
    public partial class mytrip_storesale
    {
        #region Primitive Properties
    
        public virtual int SaleId
        {
            get;
            set;
        }
    
        public virtual int Sale
        {
            get;
            set;
        }
    
        public virtual string Title
        {
            get;
            set;
        }
    
        public virtual System.DateTime CreationDate
        {
            get;
            set;
        }
    
        public virtual System.DateTime CloseDate
        {
            get;
            set;
        }
    
        public virtual string UserName
        {
            get;
            set;
        }
    
        public virtual System.DateTime StartDate
        {
            get;
            set;
        }
    
        public virtual string ManagerName
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<mytrip_storedepartment> mytrip_storedepartment
        {
            get
            {
                if (_mytrip_storedepartment == null)
                {
                    var newCollection = new FixupCollection<mytrip_storedepartment>();
                    newCollection.CollectionChanged += Fixupmytrip_storedepartment;
                    _mytrip_storedepartment = newCollection;
                }
                return _mytrip_storedepartment;
            }
            set
            {
                if (!ReferenceEquals(_mytrip_storedepartment, value))
                {
                    var previousValue = _mytrip_storedepartment as FixupCollection<mytrip_storedepartment>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupmytrip_storedepartment;
                    }
                    _mytrip_storedepartment = value;
                    var newValue = value as FixupCollection<mytrip_storedepartment>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupmytrip_storedepartment;
                    }
                }
            }
        }
        private ICollection<mytrip_storedepartment> _mytrip_storedepartment;
    
        public virtual ICollection<mytrip_storeproducer> mytrip_storeproducer
        {
            get
            {
                if (_mytrip_storeproducer == null)
                {
                    var newCollection = new FixupCollection<mytrip_storeproducer>();
                    newCollection.CollectionChanged += Fixupmytrip_storeproducer;
                    _mytrip_storeproducer = newCollection;
                }
                return _mytrip_storeproducer;
            }
            set
            {
                if (!ReferenceEquals(_mytrip_storeproducer, value))
                {
                    var previousValue = _mytrip_storeproducer as FixupCollection<mytrip_storeproducer>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupmytrip_storeproducer;
                    }
                    _mytrip_storeproducer = value;
                    var newValue = value as FixupCollection<mytrip_storeproducer>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupmytrip_storeproducer;
                    }
                }
            }
        }
        private ICollection<mytrip_storeproducer> _mytrip_storeproducer;
    
        public virtual ICollection<mytrip_storeproduct> mytrip_storeproduct
        {
            get
            {
                if (_mytrip_storeproduct == null)
                {
                    var newCollection = new FixupCollection<mytrip_storeproduct>();
                    newCollection.CollectionChanged += Fixupmytrip_storeproduct;
                    _mytrip_storeproduct = newCollection;
                }
                return _mytrip_storeproduct;
            }
            set
            {
                if (!ReferenceEquals(_mytrip_storeproduct, value))
                {
                    var previousValue = _mytrip_storeproduct as FixupCollection<mytrip_storeproduct>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupmytrip_storeproduct;
                    }
                    _mytrip_storeproduct = value;
                    var newValue = value as FixupCollection<mytrip_storeproduct>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupmytrip_storeproduct;
                    }
                }
            }
        }
        private ICollection<mytrip_storeproduct> _mytrip_storeproduct;

        #endregion
        #region Association Fixup
    
        private void Fixupmytrip_storedepartment(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (mytrip_storedepartment item in e.NewItems)
                {
                    item.mytrip_storesale = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (mytrip_storedepartment item in e.OldItems)
                {
                    if (ReferenceEquals(item.mytrip_storesale, this))
                    {
                        item.mytrip_storesale = null;
                    }
                }
            }
        }
    
        private void Fixupmytrip_storeproducer(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (mytrip_storeproducer item in e.NewItems)
                {
                    item.mytrip_storesale = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (mytrip_storeproducer item in e.OldItems)
                {
                    if (ReferenceEquals(item.mytrip_storesale, this))
                    {
                        item.mytrip_storesale = null;
                    }
                }
            }
        }
    
        private void Fixupmytrip_storeproduct(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (mytrip_storeproduct item in e.NewItems)
                {
                    item.mytrip_storesale = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (mytrip_storeproduct item in e.OldItems)
                {
                    if (ReferenceEquals(item.mytrip_storesale, this))
                    {
                        item.mytrip_storesale = null;
                    }
                }
            }
        }

        #endregion
    }
}
