//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mytrip.Mvc.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mytrip_Mvc_Language_2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mytrip_Mvc_Language_2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mytrip.Mvc.Language.Mytrip_Mvc_Language_2", typeof(Mytrip_Mvc_Language_2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (blog).
        /// </summary>
        public static string create_blog_text {
            get {
                return ResourceManager.GetString("create_blog_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are assured that wish to remove teg?.
        /// </summary>
        public static string delete_teg {
            get {
                return ResourceManager.GetString("delete_teg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To display the language panel?.
        /// </summary>
        public static string display_lang {
            get {
                return ResourceManager.GetString("display_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение регистрации по email.
        /// </summary>
        public static string email_approved {
            get {
                return ResourceManager.GetString("email_approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На email указанный Вами при регистрации выслано письмо. Вам необходимо подтвердить регистрацию перейдя по ссылке в письме..
        /// </summary>
        public static string email_approved_text1 {
            get {
                return ResourceManager.GetString("email_approved_text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо за регистрацию на сайте.
        /// </summary>
        public static string email_approved_text2 {
            get {
                return ResourceManager.GetString("email_approved_text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string folders {
            get {
                return ResourceManager.GetString("folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать рубрику статей.
        /// </summary>
        public static string menu_create_heading_article {
            get {
                return ResourceManager.GetString("menu_create_heading_article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать рубрику новостей.
        /// </summary>
        public static string menu_create_heading_news {
            get {
                return ResourceManager.GetString("menu_create_heading_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать подрубрику в рубрике статей.
        /// </summary>
        public static string menu_create_subheading_article {
            get {
                return ResourceManager.GetString("menu_create_subheading_article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать подрубрику в рубрике новостей.
        /// </summary>
        public static string menu_create_subheading_news {
            get {
                return ResourceManager.GetString("menu_create_subheading_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать рубрику статей.
        /// </summary>
        public static string menu_edit_heading_article {
            get {
                return ResourceManager.GetString("menu_edit_heading_article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать рубрику новостей.
        /// </summary>
        public static string menu_edit_heading_news {
            get {
                return ResourceManager.GetString("menu_edit_heading_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать рубрику блога.
        /// </summary>
        public static string menu_edit_heding_blog {
            get {
                return ResourceManager.GetString("menu_edit_heding_blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать подрубрику в рубрике статей.
        /// </summary>
        public static string menu_edit_subheading_article {
            get {
                return ResourceManager.GetString("menu_edit_subheading_article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать подрубрику в рубрике новостей.
        /// </summary>
        public static string menu_edit_subheading_news {
            get {
                return ResourceManager.GetString("menu_edit_subheading_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отображать для всех языков?.
        /// </summary>
        public static string view_all_culture {
            get {
                return ResourceManager.GetString("view_all_culture", resourceCulture);
            }
        }
    }
}
