//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mytrip.Mvc.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mytrip_Mvc_Language_1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mytrip_Mvc_Language_1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mytrip.Mvc.Language.Mytrip_Mvc_Language_1", typeof(Mytrip_Mvc_Language_1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the comment.
        /// </summary>
        public static string add_comment {
            get {
                return ResourceManager.GetString("add_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add on the home page?.
        /// </summary>
        public static string add_home_page {
            get {
                return ResourceManager.GetString("add_home_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tegs.
        /// </summary>
        public static string add_tegs {
            get {
                return ResourceManager.GetString("add_tegs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has added: {0}.
        /// </summary>
        public static string addedby {
            get {
                return ResourceManager.GetString("addedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree.
        /// </summary>
        public static string agree {
            get {
                return ResourceManager.GetString("agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All tegs (to add teg in article press it):.
        /// </summary>
        public static string all_tegs_article {
            get {
                return ResourceManager.GetString("all_tegs_article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All tegs (to add teg in post press it):.
        /// </summary>
        public static string all_tegs_post {
            get {
                return ResourceManager.GetString("all_tegs_post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To allocate with colour?.
        /// </summary>
        public static string allocate_color {
            get {
                return ResourceManager.GetString("allocate_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to article: .
        /// </summary>
        public static string article {
            get {
                return ResourceManager.GetString("article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To resolve comments?.
        /// </summary>
        public static string article_comment {
            get {
                return ResourceManager.GetString("article_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comments: {0}.
        /// </summary>
        public static string article_comments {
            get {
                return ResourceManager.GetString("article_comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heading: .
        /// </summary>
        public static string article_heading {
            get {
                return ResourceManager.GetString("article_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only for the registered?.
        /// </summary>
        public static string article_only_registr {
            get {
                return ResourceManager.GetString("article_only_registr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rating: {0}.
        /// </summary>
        public static string article_rating {
            get {
                return ResourceManager.GetString("article_rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subheading: .
        /// </summary>
        public static string article_subheading {
            get {
                return ResourceManager.GetString("article_subheading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tegs: .
        /// </summary>
        public static string article_tegs {
            get {
                return ResourceManager.GetString("article_tegs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to views: {0}.
        /// </summary>
        public static string article_views {
            get {
                return ResourceManager.GetString("article_views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string article1 {
            get {
                return ResourceManager.GetString("article1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article editor.
        /// </summary>
        public static string artycle_editor {
            get {
                return ResourceManager.GetString("artycle_editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To resolve voting?.
        /// </summary>
        public static string artycle_votes {
            get {
                return ResourceManager.GetString("artycle_votes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The article should contain not less than 100 symbols..
        /// </summary>
        public static string Artycles_valid_100_simbols {
            get {
                return ResourceManager.GetString("Artycles_valid_100_simbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The article cannot contain: applet.
        /// </summary>
        public static string Artycles_valid_applet {
            get {
                return ResourceManager.GetString("Artycles_valid_applet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The article cannot contain: $.
        /// </summary>
        public static string Artycles_valid_baks {
            get {
                return ResourceManager.GetString("Artycles_valid_baks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The article cannot contain: embed.
        /// </summary>
        public static string Artycles_valid_embed {
            get {
                return ResourceManager.GetString("Artycles_valid_embed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The article cannot contain: object.
        /// </summary>
        public static string Artycles_valid_object {
            get {
                return ResourceManager.GetString("Artycles_valid_object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The article cannot contain: &lt;%%&gt;.
        /// </summary>
        public static string Artycles_valid_procent {
            get {
                return ResourceManager.GetString("Artycles_valid_procent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The article cannot contain: script.
        /// </summary>
        public static string Artycles_valid_script {
            get {
                return ResourceManager.GetString("Artycles_valid_script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blog heading: .
        /// </summary>
        public static string blog_heading {
            get {
                return ResourceManager.GetString("blog_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to posts: {0}.
        /// </summary>
        public static string blog_posts {
            get {
                return ResourceManager.GetString("blog_posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blogger.
        /// </summary>
        public static string blogger {
            get {
                return ResourceManager.GetString("blogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte.
        /// </summary>
        public static string Byte {
            get {
                return ResourceManager.GetString("Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change date.
        /// </summary>
        public static string Change_date {
            get {
                return ResourceManager.GetString("Change_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfully..
        /// </summary>
        public static string change_password_text {
            get {
                return ResourceManager.GetString("change_password_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief editor.
        /// </summary>
        public static string chief_editor {
            get {
                return ResourceManager.GetString("chief_editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a heading.
        /// </summary>
        public static string chose_heding {
            get {
                return ResourceManager.GetString("chose_heding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment should contain no more than 1000 symbols..
        /// </summary>
        public static string comment_valid_1000_simbol {
            get {
                return ResourceManager.GetString("comment_valid_1000_simbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment should contain not less than 2 symbols..
        /// </summary>
        public static string comment_valid_2_simbol {
            get {
                return ResourceManager.GetString("comment_valid_2_simbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment cannot contain: applet.
        /// </summary>
        public static string comment_valid_applet {
            get {
                return ResourceManager.GetString("comment_valid_applet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment cannot contain: $.
        /// </summary>
        public static string comment_valid_baks {
            get {
                return ResourceManager.GetString("comment_valid_baks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment cannot contain: embed.
        /// </summary>
        public static string comment_valid_embed {
            get {
                return ResourceManager.GetString("comment_valid_embed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment cannot contain: object.
        /// </summary>
        public static string comment_valid_object {
            get {
                return ResourceManager.GetString("comment_valid_object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment cannot contain: &lt;%%&gt;.
        /// </summary>
        public static string comment_valid_procent {
            get {
                return ResourceManager.GetString("comment_valid_procent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment cannot contain: script.
        /// </summary>
        public static string comment_valid_script {
            get {
                return ResourceManager.GetString("comment_valid_script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string confirm_password {
            get {
                return ResourceManager.GetString("confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mytrip.Mvc  Copyright ©  2009 - 2010 Oleg Stuhin.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which it is necessary to write quantity of comments to the user for activation of its blog (comments are considered on one per every day):.
        /// </summary>
        public static string count_comment {
            get {
                return ResourceManager.GetString("count_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create folder.
        /// </summary>
        public static string create_folder {
            get {
                return ResourceManager.GetString("create_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create teg.
        /// </summary>
        public static string create_teg {
            get {
                return ResourceManager.GetString("create_teg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing date.
        /// </summary>
        public static string date_close {
            get {
                return ResourceManager.GetString("date_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are assured that wish to remove article?.
        /// </summary>
        public static string delete_article {
            get {
                return ResourceManager.GetString("delete_article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are assured that wish to remove a blog?.
        /// </summary>
        public static string delete_blog {
            get {
                return ResourceManager.GetString("delete_blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are assured that wish to remove a comment?.
        /// </summary>
        public static string delete_comment {
            get {
                return ResourceManager.GetString("delete_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are assured that wish to remove a file?.
        /// </summary>
        public static string delete_file {
            get {
                return ResourceManager.GetString("delete_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are assured that wish to remove a folder?.
        /// </summary>
        public static string delete_folder {
            get {
                return ResourceManager.GetString("delete_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are assured that wish to remove a heading?.
        /// </summary>
        public static string delete_heading {
            get {
                return ResourceManager.GetString("delete_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are assured that wish to remove news?.
        /// </summary>
        public static string delete_news {
            get {
                return ResourceManager.GetString("delete_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are assured that wish to remove a post?.
        /// </summary>
        public static string delete_post {
            get {
                return ResourceManager.GetString("delete_post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are assured that wish to remove a user?.
        /// </summary>
        public static string delete_user {
            get {
                return ResourceManager.GetString("delete_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The summary should contain not less than 3 symbols..
        /// </summary>
        public static string Description_valid_3_simbols {
            get {
                return ResourceManager.GetString("Description_valid_3_simbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The summary should contain no more than 4000 symbols..
        /// </summary>
        public static string Description_valid_4000_simbols {
            get {
                return ResourceManager.GetString("Description_valid_4000_simbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The summary cannot contain: applet.
        /// </summary>
        public static string Description_valid_applet {
            get {
                return ResourceManager.GetString("Description_valid_applet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The summary cannot contain: $.
        /// </summary>
        public static string Description_valid_baks {
            get {
                return ResourceManager.GetString("Description_valid_baks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The summary cannot contain: embed.
        /// </summary>
        public static string Description_valid_embed {
            get {
                return ResourceManager.GetString("Description_valid_embed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The summary cannot contain: object.
        /// </summary>
        public static string Description_valid_object {
            get {
                return ResourceManager.GetString("Description_valid_object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The summary cannot contain: &lt;%%&gt;.
        /// </summary>
        public static string Description_valid_procent {
            get {
                return ResourceManager.GetString("Description_valid_procent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The summary cannot contain: script.
        /// </summary>
        public static string Description_valid_script {
            get {
                return ResourceManager.GetString("Description_valid_script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain name.
        /// </summary>
        public static string Domain_name {
            get {
                return ResourceManager.GetString("Domain_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The domain name is displayed in title pages and registers in return address RSS if the domain name is entered incorrectly return references RSS will to work incorrectly (http://not to enter):.
        /// </summary>
        public static string domain_name_text {
            get {
                return ResourceManager.GetString("domain_name_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit teg.
        /// </summary>
        public static string edit_teg {
            get {
                return ResourceManager.GetString("edit_teg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email setting.
        /// </summary>
        public static string email_setting {
            get {
                return ResourceManager.GetString("email_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment Email for sending of letters from a site.
        /// </summary>
        public static string email_setting1 {
            get {
                return ResourceManager.GetString("email_setting1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GNU General Public License version 2 (GPLv2) 
        ///Copyright (C) 1989, 1991 Free Software Foundation, Inc.
        ///59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
        ///
        ///Everyone is permitted to copy and distribute verbatim copies
        ///of this license document, but changing it is not allowed.
        ///
        ///Preamble
        ///
        ///The licenses for most software are designed to take away your freedom to share and change it. By contrast, the GNU General Public License is intended to guarantee your freedom to share and change free software--to ma [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GPLv2 {
            get {
                return ResourceManager.GetString("GPLv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string hi_user {
            get {
                return ResourceManager.GetString("hi_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reference should contain no more than 256 symbols..
        /// </summary>
        public static string image_valid_256_simbols {
            get {
                return ResourceManager.GetString("image_valid_256_simbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reference cannot contain: applet.
        /// </summary>
        public static string image_valid_applet {
            get {
                return ResourceManager.GetString("image_valid_applet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reference cannot contain: $.
        /// </summary>
        public static string image_valid_baks {
            get {
                return ResourceManager.GetString("image_valid_baks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reference cannot contain: embed.
        /// </summary>
        public static string image_valid_embed {
            get {
                return ResourceManager.GetString("image_valid_embed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the absence of the reference insert null..
        /// </summary>
        public static string image_valid_null {
            get {
                return ResourceManager.GetString("image_valid_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reference cannot contain: object.
        /// </summary>
        public static string image_valid_object {
            get {
                return ResourceManager.GetString("image_valid_object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reference cannot contain: &lt;%%&gt;.
        /// </summary>
        public static string image_valid_procent {
            get {
                return ResourceManager.GetString("image_valid_procent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reference cannot contain: script.
        /// </summary>
        public static string image_valid_script {
            get {
                return ResourceManager.GetString("image_valid_script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To include articles? (Are by default included).
        /// </summary>
        public static string include_articles {
            get {
                return ResourceManager.GetString("include_articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To include blogs? (Are by default included).
        /// </summary>
        public static string include_blogs {
            get {
                return ResourceManager.GetString("include_blogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To include CAPTCHA? It (is by default included).
        /// </summary>
        public static string include_captcha {
            get {
                return ResourceManager.GetString("include_captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To include acknowledgement of the user on Email? (At inclusion you will pass to adjustment page email).
        /// </summary>
        public static string include_email {
            get {
                return ResourceManager.GetString("include_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To include acknowledgement of the user on Email? (At inclusion in the control panel there will be a reference for adjustment email).
        /// </summary>
        public static string include_email1 {
            get {
                return ResourceManager.GetString("include_email1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To include news? (Are by default included).
        /// </summary>
        public static string include_news {
            get {
                return ResourceManager.GetString("include_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose language by default for a site.
        /// </summary>
        public static string lang_setting {
            get {
                return ResourceManager.GetString("lang_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last visiting: {0}.
        /// </summary>
        public static string last_visit {
            get {
                return ResourceManager.GetString("last_visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The licence agreement.
        /// </summary>
        public static string licence {
            get {
                return ResourceManager.GetString("licence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registration.
        /// </summary>
        public static string logon_register {
            get {
                return ResourceManager.GetString("logon_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you do not have account on a site {0} take advantage of .
        /// </summary>
        public static string logon_text {
            get {
                return ResourceManager.GetString("logon_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        public static string menu_artycles {
            get {
                return ResourceManager.GetString("menu_artycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blogs.
        /// </summary>
        public static string menu_blogs {
            get {
                return ResourceManager.GetString("menu_blogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string menu_change_password {
            get {
                return ResourceManager.GetString("menu_change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a blog theme.
        /// </summary>
        public static string menu_create_blog_theme {
            get {
                return ResourceManager.GetString("menu_create_blog_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit article.
        /// </summary>
        public static string menu_edit_article {
            get {
                return ResourceManager.GetString("menu_edit_article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a blog.
        /// </summary>
        public static string menu_edit_blog {
            get {
                return ResourceManager.GetString("menu_edit_blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the comment.
        /// </summary>
        public static string menu_edit_comment {
            get {
                return ResourceManager.GetString("menu_edit_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit news.
        /// </summary>
        public static string menu_edit_news {
            get {
                return ResourceManager.GetString("menu_edit_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a post.
        /// </summary>
        public static string menu_edit_post {
            get {
                return ResourceManager.GetString("menu_edit_post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File manager.
        /// </summary>
        public static string menu_file_manager {
            get {
                return ResourceManager.GetString("menu_file_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string menu_home {
            get {
                return ResourceManager.GetString("menu_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string menu_logoff {
            get {
                return ResourceManager.GetString("menu_logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string menu_logon {
            get {
                return ResourceManager.GetString("menu_logon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management of users.
        /// </summary>
        public static string menu_management_users {
            get {
                return ResourceManager.GetString("menu_management_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string menu_news {
            get {
                return ResourceManager.GetString("menu_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string menu_register {
            get {
                return ResourceManager.GetString("menu_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string menu_search {
            get {
                return ResourceManager.GetString("menu_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site setting.
        /// </summary>
        public static string menu_site_adjustment {
            get {
                return ResourceManager.GetString("menu_site_adjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tegs.
        /// </summary>
        public static string menu_tegs {
            get {
                return ResourceManager.GetString("menu_tegs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write article.
        /// </summary>
        public static string menu_write_article {
            get {
                return ResourceManager.GetString("menu_write_article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write news.
        /// </summary>
        public static string menu_write_news {
            get {
                return ResourceManager.GetString("menu_write_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a post.
        /// </summary>
        public static string menu_write_post {
            get {
                return ResourceManager.GetString("menu_write_post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string new_password {
            get {
                return ResourceManager.GetString("new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to news: .
        /// </summary>
        public static string news {
            get {
                return ResourceManager.GetString("news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to news heading: .
        /// </summary>
        public static string news_heading {
            get {
                return ResourceManager.GetString("news_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string old_password {
            get {
                return ResourceManager.GetString("old_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ only for the registered ].
        /// </summary>
        public static string only_for_registered {
            get {
                return ResourceManager.GetString("only_for_registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quantity on page.
        /// </summary>
        public static string pager_count {
            get {
                return ResourceManager.GetString("pager_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pages.
        /// </summary>
        public static string pager_pages {
            get {
                return ResourceManager.GetString("pager_pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url a photo to the article.
        /// </summary>
        public static string photo_article {
            get {
                return ResourceManager.GetString("photo_article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo to the summary as a photo to article?.
        /// </summary>
        public static string photo_article_summary {
            get {
                return ResourceManager.GetString("photo_article_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url a photo to the summary.
        /// </summary>
        public static string photo_summary {
            get {
                return ResourceManager.GetString("photo_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to post: .
        /// </summary>
        public static string post {
            get {
                return ResourceManager.GetString("post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blog: .
        /// </summary>
        public static string post_blog {
            get {
                return ResourceManager.GetString("post_blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration of the admin of a site.
        /// </summary>
        public static string reg_admin {
            get {
                return ResourceManager.GetString("reg_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration of users.
        /// </summary>
        public static string reg_users {
            get {
                return ResourceManager.GetString("reg_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords are required to be a minimum of {0} characters in length..
        /// </summary>
        public static string register_text {
            get {
                return ResourceManager.GetString("register_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string rememberme {
            get {
                return ResourceManager.GetString("rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results of search.
        /// </summary>
        public static string results_search {
            get {
                return ResourceManager.GetString("results_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before activation of your blog remains comments: {0} &lt;small&gt;(comments written to one day are not considered)&lt;/small&gt;.
        /// </summary>
        public static string right_activation_blog {
            get {
                return ResourceManager.GetString("right_activation_blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control panel.
        /// </summary>
        public static string right_control_panel {
            get {
                return ResourceManager.GetString("right_control_panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a blog.
        /// </summary>
        public static string right_create_blog {
            get {
                return ResourceManager.GetString("right_create_blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string right_menu_user {
            get {
                return ResourceManager.GetString("right_menu_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site roles (to add a role to the user press it):.
        /// </summary>
        public static string roles_site {
            get {
                return ResourceManager.GetString("roles_site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles of the user (to remove a role press it):.
        /// </summary>
        public static string roles_user {
            get {
                return ResourceManager.GetString("roles_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in the User Name or Email:.
        /// </summary>
        public static string search_users {
            get {
                return ResourceManager.GetString("search_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string size {
            get {
                return ResourceManager.GetString("size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string summary {
            get {
                return ResourceManager.GetString("summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tegs articles (to remove teg from article press it):.
        /// </summary>
        public static string tegs_article {
            get {
                return ResourceManager.GetString("tegs_article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tegs a post (to remove teg from a post press it):.
        /// </summary>
        public static string tegs_post {
            get {
                return ResourceManager.GetString("tegs_post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        public static string text_align_css {
            get {
                return ResourceManager.GetString("text_align_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        public static string text_direction {
            get {
                return ResourceManager.GetString("text_direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title should contain no more than 256 symbols..
        /// </summary>
        public static string title_valid_256_simbols {
            get {
                return ResourceManager.GetString("title_valid_256_simbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title should contain not less than 3 symbols..
        /// </summary>
        public static string title_valid_3_simbols {
            get {
                return ResourceManager.GetString("title_valid_3_simbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title cannot contain: applet.
        /// </summary>
        public static string title_valid_applet {
            get {
                return ResourceManager.GetString("title_valid_applet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title cannot contain: $.
        /// </summary>
        public static string title_valid_baks {
            get {
                return ResourceManager.GetString("title_valid_baks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title cannot contain: embed.
        /// </summary>
        public static string title_valid_embed {
            get {
                return ResourceManager.GetString("title_valid_embed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title cannot contain: object.
        /// </summary>
        public static string title_valid_object {
            get {
                return ResourceManager.GetString("title_valid_object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title cannot contain: &lt;%%&gt;.
        /// </summary>
        public static string title_valid_procent {
            get {
                return ResourceManager.GetString("title_valid_procent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title cannot contain: script.
        /// </summary>
        public static string title_valid_script {
            get {
                return ResourceManager.GetString("title_valid_script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In total it is registered: {0}.
        /// </summary>
        public static string total_registered {
            get {
                return ResourceManager.GetString("total_registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string upload {
            get {
                return ResourceManager.GetString("upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file.
        /// </summary>
        public static string upload_file {
            get {
                return ResourceManager.GetString("upload_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online: {0}.
        /// </summary>
        public static string user_online {
            get {
                return ResourceManager.GetString("user_online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying phrase.
        /// </summary>
        public static string verifying_phrase {
            get {
                return ResourceManager.GetString("verifying_phrase", resourceCulture);
            }
        }
    }
}
