//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace mtm.Core.Repository.DataEntities
{
    public partial class mytrip_geocountry
    {
        #region Primitive Properties
    
        public virtual int CountryId
        {
            get;
            set;
        }
    
        public virtual string Code
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> Longitude
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> Latitude
        {
            get;
            set;
        }
    
        public virtual bool EditAdmin
        {
            get;
            set;
        }
    
        public virtual bool EditUser
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<mytrip_georegion> mytrip_georegion
        {
            get
            {
                if (_mytrip_georegion == null)
                {
                    var newCollection = new FixupCollection<mytrip_georegion>();
                    newCollection.CollectionChanged += Fixupmytrip_georegion;
                    _mytrip_georegion = newCollection;
                }
                return _mytrip_georegion;
            }
            set
            {
                if (!ReferenceEquals(_mytrip_georegion, value))
                {
                    var previousValue = _mytrip_georegion as FixupCollection<mytrip_georegion>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupmytrip_georegion;
                    }
                    _mytrip_georegion = value;
                    var newValue = value as FixupCollection<mytrip_georegion>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupmytrip_georegion;
                    }
                }
            }
        }
        private ICollection<mytrip_georegion> _mytrip_georegion;

        #endregion
        #region Association Fixup
    
        private void Fixupmytrip_georegion(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (mytrip_georegion item in e.NewItems)
                {
                    item.mytrip_geocountry = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (mytrip_georegion item in e.OldItems)
                {
                    if (ReferenceEquals(item.mytrip_geocountry, this))
                    {
                        item.mytrip_geocountry = null;
                    }
                }
            }
        }

        #endregion
    }
}
