//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace mtm.Core.Repository.DataEntities
{
    public partial class mytrip_corepages
    {
        #region Primitive Properties
    
        public virtual int PageId
        {
            get;
            set;
        }
    
        public virtual string Title
        {
            get;
            set;
        }
    
        public virtual string Path
        {
            get;
            set;
        }
    
        public virtual string SeoTitle
        {
            get;
            set;
        }
    
        public virtual string SeoKeyword
        {
            get;
            set;
        }
    
        public virtual string SeoDescription
        {
            get;
            set;
        }
    
        public virtual string Body
        {
            get;
            set;
        }
    
        public virtual bool ViewOnlyHomePage
        {
            get;
            set;
        }
    
        public virtual bool SideBar
        {
            get;
            set;
        }
    
        public virtual bool EmailForm
        {
            get;
            set;
        }
    
        public virtual bool AddMenu
        {
            get;
            set;
        }
    
        public virtual bool AddHomePage
        {
            get;
            set;
        }
    
        public virtual string Culture
        {
            get;
            set;
        }
    
        public virtual bool AllCulture
        {
            get;
            set;
        }
    
        public virtual int SubPagesId
        {
            get { return _subPagesId; }
            set
            {
                if (_subPagesId != value)
                {
                    if (mytrip_corepages2 != null && mytrip_corepages2.PageId != value)
                    {
                        mytrip_corepages2 = null;
                    }
                    _subPagesId = value;
                }
            }
        }
        private int _subPagesId;

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<mytrip_corepages> mytrip_corepages1
        {
            get
            {
                if (_mytrip_corepages1 == null)
                {
                    var newCollection = new FixupCollection<mytrip_corepages>();
                    newCollection.CollectionChanged += Fixupmytrip_corepages1;
                    _mytrip_corepages1 = newCollection;
                }
                return _mytrip_corepages1;
            }
            set
            {
                if (!ReferenceEquals(_mytrip_corepages1, value))
                {
                    var previousValue = _mytrip_corepages1 as FixupCollection<mytrip_corepages>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupmytrip_corepages1;
                    }
                    _mytrip_corepages1 = value;
                    var newValue = value as FixupCollection<mytrip_corepages>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupmytrip_corepages1;
                    }
                }
            }
        }
        private ICollection<mytrip_corepages> _mytrip_corepages1;
    
        public virtual mytrip_corepages mytrip_corepages2
        {
            get { return _mytrip_corepages2; }
            set
            {
                if (!ReferenceEquals(_mytrip_corepages2, value))
                {
                    var previousValue = _mytrip_corepages2;
                    _mytrip_corepages2 = value;
                    Fixupmytrip_corepages2(previousValue);
                }
            }
        }
        private mytrip_corepages _mytrip_corepages2;

        #endregion
        #region Association Fixup
    
        private void Fixupmytrip_corepages2(mytrip_corepages previousValue)
        {
            if (previousValue != null && previousValue.mytrip_corepages1.Contains(this))
            {
                previousValue.mytrip_corepages1.Remove(this);
            }
    
            if (mytrip_corepages2 != null)
            {
                if (!mytrip_corepages2.mytrip_corepages1.Contains(this))
                {
                    mytrip_corepages2.mytrip_corepages1.Add(this);
                }
                if (SubPagesId != mytrip_corepages2.PageId)
                {
                    SubPagesId = mytrip_corepages2.PageId;
                }
            }
        }
    
        private void Fixupmytrip_corepages1(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (mytrip_corepages item in e.NewItems)
                {
                    item.mytrip_corepages2 = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (mytrip_corepages item in e.OldItems)
                {
                    if (ReferenceEquals(item.mytrip_corepages2, this))
                    {
                        item.mytrip_corepages2 = null;
                    }
                }
            }
        }

        #endregion
    }
}
